### ISSUE TITLE
Encoding and thumbfast

### ISSUE THREAD

**Issue by hooke007** [mpvnet-player/mpv.net#387]
For `mpv.com` , it could do a quick transcoding via the command below.
```
mpv --o=output_file.mkv input_file.mp4
```
However, I found it cannot do it by `mpvnet --o=output_file.mkv input_file.mp4` . It just started the program and played the file.

**Comment by stax76** [comment]
It might be possible to do after changes, but it's not a simple task, it will take time until I start working on it.

**Comment by hooke007** [comment]
Feel free to decide when to implement it. I don't have a strong demand for this function.

**Comment by stax76** [comment]
@dyphire 

In the last commit and auto build is:

- Support for encoding mode and thumbfast.
- For script authors, the following info is available in user-data:  
  user-data/frontend/name=mpv.net  
  user-data/frontend/version=the version name  
  user-data/frontend/process-path=the process path
