### ISSUE TITLE
Audio can't be heard after version 6.0.1.0 (working fine on v6.0.0.0-beta)

### ISSUE THREAD

**Issue by ThomasEricB** [mpvnet-player/mpv.net#462]
**Describe the bug**
Audio doesn't play after the first second of video. (EDIT: LOG FILES BELOW)

**To Reproduce**
1. Open a .mp4 file
2. Audio pops for a second and then stops
3. Audio-less video

**Expected behavior**
The video's audio track to be played and be heard. 

**Screenshots**
![ZQnt8hdVSh](https://user-images.githubusercontent.com/9662095/178131725-90122213-cf8a-4788-8671-8c5e9023bf60.png)

**Additional context**
I can reproduce the bug with certainty on [v6.0.1.0,](https://github.com/stax76/mpv.net/releases/tag/v6.0.1.0) [v6.0.2.0](https://github.com/stax76/mpv.net/releases/tag/v6.0.2.0) and [v6.0.3.0](https://github.com/stax76/mpv.net/releases/tag/v6.0.3.0) [Latest](https://github.com/stax76/mpv.net/releases/latest). Not happening [v6.0.0.0-beta](https://github.com/stax76/mpv.net/releases/tag/v6.0.0.0-beta) which is why I'm staying with this version for now... Might be a Libmpv bug, not sure @stax76 (EDIT LOG FILES BELOW)

**Comment by ThomasEricB** [comment]
Here are some logs of me opening the same file with the audio working and not working:
[log WITH AUDIO BETA VERSION.txt](https://github.com/stax76/mpv.net/files/9078481/log.WITH.AUDIO.BETA.VERSION.txt)
[log NO AUDIO LATEST VERSION.txt](https://github.com/stax76/mpv.net/files/9078482/log.NO.AUDIO.LATEST.VERSION.txt)

**Comment by stax76** [comment]
Can you maybe upload the .mp4 file?

**Comment by ThomasEricB** [comment]
Nop, I can't as it is a 1970 BBC show

**Comment by ThomasEricB** [comment]
Still cannot hear any audio... Even with no scripts and a clean .conf

**Comment by ThomasEricB** [comment]
All this time it was because I was using outdated versions of the Filter_Audio and Filter_Audio_ScaleTempo lua scripts by deus0ww. Sorry @stax76 , this had nothing to do with MPV.net
