### ISSUE TITLE
Open folders using relative path

### ISSUE THREAD

**Issue by tunaflsh** [mpvnet-player/mpv.net#496]
**Describe the bug**
When passing a folder to mpvnet in CLI specified by relative path, the player doesn't create a playlist.

**To Reproduce**
1. Put videos into the current folder.
2. Run `mpvnet .` or `mpvnet ..\current_folder`

**Expected behavior**
The player should create a playlist from the folder.

**Additional context**
1. mpv.net version 6.0.3.0 and 6.0.3.1 (I haven't tried older releases)
2. Windows version 10 Home 21H2

The `mpv` works fine with relative path.

**Comment by stax76** [comment]
It's supported in the next release.
