### ISSUE TITLE
Command palette playlist title name

### ISSUE THREAD

**Issue by bfusil** [mpvnet-player/mpv.net#509]
I use a m3u streaming playlist to watch TV channels and the **command palette playlist** (F8 key) feature is great, as it allows me to select the desired channel and not just go to next or previous, which is not practicable when you have dozens or hundreds of streams.

The problem is the command palette playlist only shows the URL end name:
![Capture d’écran 2022-11-15 084910](https://user-images.githubusercontent.com/84630072/201860454-ae25775b-7174-4f55-8f75-260db6d8fd71.jpg)

Is there a way to show the #EXTINF info from a m3u file playlist in the command palette playlist?

**Comment by Torben2000** [comment]
I have exactly the same use case and exactly that same issue with the current implementation.
So I implemented it and created a pull request. 😄

**Comment by Torben2000** [comment]
Yes, it was merged on January 21st 2023 (in fact it was the very last change so you can even see it on the front page of this repo).
The latest version and the latest beta release are both from 2022 so it cannot be in those. :-)
If you really need this feature, you need to build the software on your own or convince @stax76 to release a new version.
