### ISSUE TITLE
Is there a way to build mpv.net with latest mpv?

### ISSUE THREAD

**Issue by HxxThSwggr** [mpvnet-player/mpv.net#512]
I have some issues that seem to be fixed in a newer version of mpv.
I want to use mpv.net but dont want to wait for a new release.

Is there a way for me to build mpv.net master with latest mpv?

**Comment by zhongfly** [comment]
Just replace libmpv-2.dll, no need to build.
You can download it from shinchiro with `mpv-dev-` prefix

**Comment by HxxThSwggr** [comment]
Ahh very nice. Thx!

**Comment by MisakaSakura** [comment]
> Just replace `mpv-2.dll` in mpvnet dir, no need to build. You can download from [shinchiro's build](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/) or [my build](https://github.com/zhongfly/mpv-winbuild/releases) with `mpv-dev-` prefix. For example,[mpv-dev-x86_64-v3-20221120-git-f10b24e.7z](https://github.com/zhongfly/mpv-winbuild/releases/download/2022-11-20/mpv-dev-x86_64-v3-20221120-git-f10b24e.7z)

 But the latest build of shinchiro doesn't have mpv-2.dll, now how can we update mpvnet by replacing the file?

**Comment by zhongfly** [comment]
> > Just replace `mpv-2.dll` in mpvnet dir, no need to build. You can download from [shinchiro's build](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/) or [my build](https://github.com/zhongfly/mpv-winbuild/releases) with `mpv-dev-` prefix. For example,[mpv-dev-x86_64-v3-20221120-git-f10b24e.7z](https://github.com/zhongfly/mpv-winbuild/releases/download/2022-11-20/mpv-dev-x86_64-v3-20221120-git-f10b24e.7z)
> 
> But the latest build of shinchiro doesn't have mpv-2.dll, now how can we update mpvnet by replacing the file?

you can rename `libmpv-2.dll` to `mpv-2.dll`,nothing else need to do

**Comment by MisakaSakura** [comment]
> > > Just replace `mpv-2.dll` in mpvnet dir, no need to build. You can download from [shinchiro's build](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/) or [my build](https://github.com/zhongfly/mpv-winbuild/releases) with `mpv-dev-` prefix. For example,[mpv-dev-x86_64-v3-20221120-git-f10b24e.7z](https://github.com/zhongfly/mpv-winbuild/releases/download/2022-11-20/mpv-dev-x86_64-v3-20221120-git-f10b24e.7z)
> > 
> > 
> > But the latest build of shinchiro doesn't have mpv-2.dll, now how can we update mpvnet by replacing the file?
> 
> you can rename `libmpv-2.dll` to `mpv-2.dll` before mpv.net update its code related to old file name It's just a name change,nothing else change
> 
> I have opened an issue to mpv.net related to this problem #528

I don't quite understand because the mpv-x86_64-v3-20230120-git-67dbe2a.7z package I downloaded doesn't contain libmpv-2.dll or mpv-2.dll files, only a dll file named d3dcompiler_43.dll.

**Comment by zhongfly** [comment]
> I don't quite understand because the mpv-x86_64-v3-20230120-git-67dbe2a.7z package I downloaded doesn't contain libmpv-2.dll or mpv-2.dll files, only a dll file named d3dcompiler_43.dll.

> with `mpv-dev-` prefix

please read carefully

**Comment by MisakaSakura** [comment]
> > I don't quite understand because the mpv-x86_64-v3-20230120-git-67dbe2a.7z package I downloaded doesn't contain libmpv-2.dll or mpv-2.dll files, only a dll file named d3dcompiler_43.dll.
> 
> > with `mpv-dev-` prefix
> 
> Please read the previous reply carefully, you have downloaded the wrong file
> 
> [mpv-dev-x86_64-v3-20230120-git-67dbe2a.7z](https://github.com/zhongfly/mpv-winbuild/releases/download/2023-01-20/mpv-dev-x86_64-v3-20230120-git-67dbe2a.7z)

Missed it, my bad, thanks

**Comment by candrapersada** [comment]
add `lua51.dll` aftar `mpv-2.dll` or `libmpv-2.dll`
