### ISSUE TITLE
Is it possible to change the position of "seek-show-position.js" to Top Right instead of Top Left?

### ISSUE THREAD

**Issue by BhaturaGuy** [mpvnet-player/mpv.net#518]
Current position gets in the way when switching chapters and looks ugly.
![image](https://user-images.githubusercontent.com/93109835/205477792-8594e1fb-eab3-49d8-8ed3-ffba9f926e30.png)

**Comment by stax76** [comment]
I'm not well-informed about font rendering and have never seen a script that renders something on the right side.

Likely, you change chapters with a command, from input.conf you can bind multiple commands simply by separating them with a semicolon, so you can clear the OSD message before you invoke your chapter command.

<key> command 1; command 2

You can clear the OSD with the command `show-text ''`.

**Comment by BhaturaGuy** [comment]
> You can clear the OSD with the command show-text ''

Doesn't make a difference. 

Is it possible for the script not do anything when I use `add chapter  1` and `add chapter  -1`

**Comment by stax76** [comment]
The script acts upon the seek event, it cannot know what has triggered the seek event, so no, not possible.

**Comment by BhaturaGuy** [comment]
https://github.com/Eisa01/mpv-scripts#simplehistory
This is the only script I found that can render the list at any location
see https://github.com/Eisa01/mpv-scripts/blob/master/script-opts/SimpleHistory.conf#L147 
Maybe the same can be implemented using this as a reference?

**Comment by stax76** [comment]
I rewrote this now and hope it's better, you can find it here:

https://github.com/stax76/mpv-scripts/blob/main/misc.lua

It works differently now, input.conf must be changed:

`Right no-osd seek 5; script-message-to misc show-position`

Don't forget to remove `seek-show-position.js`.
