### ISSUE TITLE
MPVMediaControl plugin works inconsistently and thumbnails do not appear at all

### ISSUE THREAD

**Issue by rollingmoai** [mpvnet-player/mpv.net#523]
**Describe the bug**
The [MPVMediaControl](https://github.com/datasone/MPVMediaControl) plugin works inconsistently, and thumbnails do not appear at all.

**To Reproduce**

1. Open mpv.net
2. Open a file
3. SMTC Controls appear but will either sometimes work or be non-responsive. `Reset SMTC` does not help fix the problem. Thumbnail also doesn't appear
5. Close mpv.net
6. Repeat the process and see it inconsistently work (or not)

**Expected behavior**
Thumbnails should appear and should work consistently as expected. The plugin works as expected in MPV.

**Alternative Solution**
Maybe we can get this feature built-in to mpv.net instead.

**Additional context**
Related to #299.

P.S., @datasone maybe you can help in investigating this issue?

**Comment by sitiom** [comment]
See https://github.com/datasone/MPVMediaControl/issues/11. For thumbnails, I think it is a different issue.

**Comment by datasone** [comment]
After some investigation, I think the issues don't come from mpv.net side (though some differences between vanilla and mpv.net triggered the issues).

It's now basically solved and more detailed in datasone/MPVMediaControl#12.

**Comment by rollingmoai** [comment]
Now works as intended, thanks!
