### ISSUE TITLE
Playlist-shuffle is not uniquely random

### ISSUE THREAD

**Issue by pragma-** [mpvnet-player/mpv.net#531]
When I use the `playlist-shuffle` command via the `s` key-bind, the playlist shuffles in the same random order. I have to press `s` a random number of times to get a unique shuffle. Am I misunderstanding what `playlist-shuffle` is supposed to do? I'm expecting a completely unique random shuffle the first time I press `s`.

**Comment by stax76** [comment]
You can request support for this on the mpv issue tracker.
