### ISSUE TITLE
Left mouse down triggers mouse up event

### ISSUE THREAD

**Issue by intelligentcow2** [mpvnet-player/mpv.net#533]
Clicking the left mouse button on the mpv.net window immediately sends a mouse down and mouse up event, regardless of how long the mouse button is held.

**Steps to reproduce the behavior:**
Add the following lua script
```
function log(arg)
    mp.msg.error(arg.event)
    mp.osd_message(arg.event)
end

mp.add_forced_key_binding("MBTN_LEFT", nil, log, {complex = true})
```
Start mpv.net and click and hold the left mouse button on its window. The key binding will be triggered twice in rapid succession, first with arg.event == down and then up. Releasing the mouse button will not trigger the key binding.

**Expected behavior**
Clicking the left mouse button should not trigger the mouse up event until it is released. This is what happens in mpv and also in mpv.net with the right and middle mouse buttons.

**Comment by stax76** [comment]
I hope it is fixed in the last beta release.
