### ISSUE TITLE
Hello! Can't play YouTube video ...

### ISSUE THREAD

**Issue by zhouxinghong** [mpvnet-player/mpv.net#537]
Hello! Can't play YouTube videos
But youtube can be played in edge browser...
win10
The latest version

**Comment by aicynide** [comment]
Grab mpv-2.dll from https://github.com/dyphire/mpv-winbuild-cmake

**Comment by User486375** [comment]
> Hello! Can't play YouTube videos But youtube can be played in edge browser... win10 The latest version

You need the latest [yt-dlp](https://github.com/yt-dlp/yt-dlp/releases) executable in either the mpv.net program folder `C:\Program Files\mpv.net` or have it added to path.

> Grab mpv-2.dll from https://github.com/dyphire/mpv-winbuild/releases/download/mpv_own-2023-04-06/mpv-dev-x86_64-v3-20230406-git-eb3d5cc.7z

@aicynide 

Dyphire builds don't work on the latest beta. Shinchiro builds do however, which it was released with https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230508/mpv-dev-x86_64-v3-20230508-git-a1580b6.7z
However the latest mpv dll is not even required to play youtube videos.

**Comment by zhouxinghong** [comment]
Tried according to your method, still can't play YouTube
