### ISSUE TITLE
Release new stable version of mpv.net

### ISSUE THREAD

**Issue by soredake** [mpvnet-player/mpv.net#539]
Right now there is no stable version with new features/bugfixes from two last beta version.

@stax76

**Comment by User486375** [comment]
A workaround to this is to install [5.4.9.0](https://github.com/mpvnet-player/mpv.net/releases/tag/5.4.9.0) and drag and drop replace the contents of [6.0.3.2-beta](https://github.com/mpvnet-player/mpv.net/releases/tag/v6.0.3.2-beta) into `C:\Program Files\mpv.net`.

This can probably also be done with the store version, but requires the effort of modifying folder permissions and reduces app/OS security. There's no advantage to doing so though.

**Comment by soredake** [comment]
I've just install beta version of mpv.net from chocolatey for now.

**Comment by soredake** [comment]
@stax76 mpvnet really needs new release, youtube videos don't have sound now as `ytdl_hook.lua` is needs to be updated to support newer yt-dlp version:
https://github.com/yt-dlp/yt-dlp/issues/6496
https://github.com/mpv-player/mpv/issues/11392

**Comment by soredake** [comment]
@stax76 thank you!
