### ISSUE TITLE
Is there a way to get mpv display the auto-generated subtitle using yt-dlp

### ISSUE THREAD

**Issue by Xelbayria** [mpvnet-player/mpv.net#545]
**Describe the problem**
yt-dlp and mpv.net are used to stream a video from Youtube. Most videos has auto-generated subtitles, rarely has subtitle created by someone else. 

I was testing out with mpv.net and it was an excellent BUT I discovered that it doesn't have the feature to display the auto-generated subtitle (most youtube videos has them). Potplayer or VLC can play with displaying auto-generated subtitles without any problem. 

I've set the config: 
sub-auto= fuzzy
sub-lang | slang = en

Case#1:
I played https://youtu.be/i6kccBc-FBQ 

NOTE: it has Auto-generated Subtitle (en)

Case#2:
I also played https://youtu.be/gAYzBJxOeLw

NOTE: the subtitle show up because it's English which is created by someone else (en-GB). Another note: is the "auto-generated subtitle" should have show up.  (en) and (en-GB) making 2 subtitles. The example is in the picture below. 

The problem is Auto-generated subtitle is not show up, how do I get it show up? 

---

**To Reproduce**

open CMD or Powershell (either works fine). 
Case#1: 
run `mpvnet.exe "ytdl://youtu.be/i6kccBc-FBQ" ytdl-raw-options=sub-lang="en",write-sub=,write-auto-sub=`

Case#2:
run `mpvnet.exe "ytdl://youtu.be/gAYzBJxOeLw" ytdl-raw-options=sub-lang="en",write-sub=,write-auto-sub=`

In case of an audio or video problem, try to reproduce the problem using mpv instead of mpv.net.
If it can be reproduced with mpv, use the [mpv issue tracker](https://github.com/mpv-player/mpv/issues).

**Expected behavior**
I expected to see the "auto-generated subtitle" to show up in the video just like "en-GB" did. 

**Screenshots**
Case#1: 
![image](https://github.com/mpvnet-player/mpv.net/assets/12866666/e4218dae-460d-4091-a064-c9d99b3084d4)

Case#2: 
![image](https://github.com/mpvnet-player/mpv.net/assets/12866666/b7675631-750a-46e7-a338-1cfabf0c72cc)

**Additional context**
1. mpv.net version: 6.0.3.0
2. Windows version: 10 Pro (64bit)
3. yt-dlp version:  2023-06-24

**Comment by tunaflsh** [comment]
I think the problem is not related to mpvnet, but how [yt-dlp](https://github.com/yt-dlp/yt-dlp#subtitle-options) behaves. The sub-lang option matches regex, so you need **"en.*"** to match all "en" related subtitles. `sub-lang="en"` will match "en" exactly and won't download "en-US", "en-GB" etc.

**Note**: yt-dlp finds more automatic captions than are available in Youtube. So you can get captions auto-translated to other languages. But even "en.*" has several different auto-captions. And I have no idea which is the one displayed on Youtube.
To check all available subtitles you can run `yt-dlp --list-subs <URL>`

To answer your question:
run `mpvnet.exe "ytdl://<url>" ytdl-raw-options=sub-lang="en.*",write-sub=,write-auto-sub=`
or put the following into mpv.conf:
```config
ytdl-raw-options=sub-lang="en.*",write-sub=,write-auto-sub=
```

**Comment by Xelbayria** [comment]
> I think the problem is not related to mpvnet, but how [yt-dlp](https://github.com/yt-dlp/yt-dlp#subtitle-options) behaves. The sub-lang option matches the regex, so you need **"en.*"** to match all "en" related subtitles. `sub-lang="en"` will match "en" exactly and won't download "en-US", "en-GB" etc.
> 
> **Note**: yt-dlp finds more automatic captions than are available in Youtube. So you can get captions auto-translated to other languages. But even "en.*" has several different auto-captions. And I have no idea which is the one displayed on Youtube. To check all available subtitles you can run `yt-dlp --list-subs <URL>`
> 
> To answer your question: run `mpvnet.exe "ytdl://<url>" ytdl-raw-options=sub-lang="en.*",write-sub=,write-auto-sub=` or put the following into mpv.conf:
> 
> ```
> ytdl-raw-options=sub-lang="en.*",write-sub=,write-auto-sub=
> ```

tbh, I agree with you that it's yt-dlp. It would be nice if yt-dlp could display the name of the subtitle I am using. This way, I'll know if I use auto-generated or created subtitles. I'll try `en.*` and see if that works. 

---
alright, I'm back & you were right, `en.*` find other subtitles and add them to the list of subtitles. so I got `-/4` instead of `-/1`

Consider this to be closed. Thanks for pointing out the problem and solving it. I remember `en.*` and forgot about it, lol
