### ISSUE TITLE
Title bar color doesn't follow system theme on Windows 11

### ISSUE THREAD

**Issue by Solarflame5** [mpvnet-player/mpv.net#546]
**Describe the bug**
All UWP apps and Win32 apps that support it have a dark colored title bar on windows 11 if your system theme is set to dark, but mpv.net always uses the light colored title bar

**To Reproduce**
1. Set windows color theme to dark
2. Launch mpv.net
3. Title bar is still light colored

**Expected behavior**
The title bar should be dark colored, like the other apps shown in the screenshot below

**Screenshots**
![image](https://github.com/mpvnet-player/mpv.net/assets/47642904/68d701f6-0231-4b4f-8f9a-ddf6e36b8020)

**Additional context**
1. mpv.net version: 6.0.3.0
2. Windows version: Windows 11 22H2(build 22621.1848)

**Comment by stax76** [comment]
I hope it's fixed in the beta release from today.
