### ISSUE TITLE
PGS Subtitles broken on v6.0.4.0-stable

### ISSUE THREAD

**Issue by ll811** [mpvnet-player/mpv.net#561]
**Describe the bug**
Subtitles will stick to the screen until the next line of dialogue is delivered, so if there's 20 seconds of silence between dialogue, the subtitle will stick to the screen until the next in line comes. This occurs with PGS subtitles, in my limited testing it seems SRT works as intended.

1. Start any video that has PGS subtitles
2. Wait for a space between dialogue 
3. See error

**Comment by stax76** [comment]
The bug appeared 3 weeks ago, as pointed out on the mpv tracker here:

https://github.com/mpv-player/mpv/issues/12327

I was able to reproduce it with the first movie tried.

There are older libmpv builds available, for instance here:

https://github.com/zhongfly/mpv-winbuild/releases/download/2023-07-31/mpv-dev-x86_64-20230731-git-b3b7ee8.7z

**Comment by rtabulov** [comment]
the fix is already in mpv [v0.37.0](https://github.com/mpv-player/mpv/releases/tag/v0.37.0)

**Comment by stax76** [comment]
Here is a guide explaining how to update libmpv:

https://github.com/mpvnet-player/mpv.net/discussions/603
