### ISSUE TITLE
Cycle aspect ratio no longer works in 6.0.4.0

### ISSUE THREAD

**Issue by Fukeung** [mpvnet-player/mpv.net#563]
I tried with clean input.conf.

**Comment by ashibrehmanb** [comment]
Hello Fukeung. To fix this issue go to `input.conf` and change `video-aspect` to `video-aspect-override`

Before: `a           cycle-values video-aspect 16:9 4:3 2.35:1 -1`

After: `a           cycle-values video-aspect-override 16:9 4:3 2.35:1 -1`

**Comment by zhongfly** [comment]
https://github.com/mpv-player/mpv/commit/3ab5401b38d1ff1c1bb85f108f26d508cc334c82
`video-aspect` was marked as deprecated and replaced by `video-aspect-override` 4 years ago, and was completely removed in September.

**Comment by stax76** [comment]
It's fixed in the upcoming release.
