### ISSUE TITLE
watch later does not work (save-position-on-quit & shift+q)

### ISSUE THREAD

**Issue by BillyBob1354** [mpvnet-player/mpv.net#565]
watch later does not work. ("save-position-on-quit" & shift+q). Resume files created in the "watch_later" folder are blank.

mpv.net v6.0.4.0

**Comment by stax76** [comment]
I was able to reproduce it, then updated libmpv to zhongfly 2023-12-11 and with that it's fine. I had forgotten to update to a newer build.
