### ISSUE TITLE
Issues with redesigned bindings and context menu

### ISSUE THREAD

**Issue by stax76** [mpvnet-player/mpv.net#572]
Posted by Sneakpeakcss [here](https://github.com/mpvnet-player/mpv.net/issues/567#issuecomment-1781945163).

## Few issues after the new `Redesigned bindings and context menu`.
In changelog it's mentioned that `"Defining the context menu in input.conf is still supported, but discouraged and undocumented."`, this created few issues/incompatibilities:

From what i understand, it's expected now to use `Show input editor` to define bindings or build context menu. 

- You can't use more than one modifier key when using `Input editor`, i.e. `Ctrl+Alt+A` is impossible to make.
- `Learn input` popout only shows up when either `command` was already written, or you first activate `name` or `command` columns, and then jump back to it. 
- It would also be good if the popout had the typical "press any key" placeholder so it doesn't look like an empty box, but that's purely visual.
- `Input editor` only creates the command properly if it's defined from right to left, trying to create a name first just bugs out after pressing enter, showing no changes in editor, but still creating an 'empty binding' at the end of `input.conf'.

https://github.com/mpvnet-player/mpv.net/assets/77424331/a2cd6ccc-fc67-4cdf-92f4-5c0310562a07

       And this is what shows up in `input.conf` when it's not defined in right->left order:
```
_           ignore
_           ignore
_           test
h           ignore
h           test
```

- Another new(?) issue is simmilar to [#538 ](https://github.com/mpvnet-player/mpv.net/issues/538). When any new bind is added through `Input editor` it removes any commented-out and empty lines, so not only it deletes users formating, it also removes any "turned off" bindings. Basically deleting anything that starts with `#` without any notification to the user. This makes `input.conf` file mostly exclusive to `mpv.net`, and has potential config loss for the user.
 
![image](https://github.com/mpvnet-player/mpv.net/assets/77424331/04d575b4-bc42-4bbc-9342-7900e04b723c)

       It even removes old separators in main context menu, but not submenus:

![image](https://github.com/mpvnet-player/mpv.net/assets/77424331/e305467e-ad9e-44bf-808e-bc69b1173864)

       also changes old `#menu:` syntax and replaces it with `# menu:` which potentailly adds up to another issue:

- Uosc menu [syntax](https://github.com/tomasklaen/uosc#examples) is now broken for both uosc's compatibility `#menu:` and their native `#!` menu defining prefixes. Right now uosc doesn't even recognize it's own `#!` syntax, and outputs only it's own hardcoded default menu. This happens no matter if using old `input.conf` before `Input editor` goes through it removing stuff.

I'm also not 100% sure if all those `Input editor` issues are new, i've never used it before because i always did every editing manually in `input.conf`
___
 

And i'm not certain, but while `mpv.net` still has `Customizable context menu defined in the same file as the key bindings` in description, there's also this in changelog 

> Redesigned bindings and context menu, the default bindings and context menu are now defined internally, no longer is a default input.conf file generated. It means mpv.net no longer loses control over the default bindings and menu 

does this mean that creating personal context menu functionality is mostly unsupported now, even through editor ? No matter what i've tried i couldn't create anything using the editor, since it just deletes anything in `Name` column after reopening:

![image](https://github.com/mpvnet-player/mpv.net/assets/77424331/cf004beb-0d73-4c69-9a11-29c46efeeedd)

After reopening:

![image](https://github.com/mpvnet-player/mpv.net/assets/77424331/16bac271-aa35-4828-abc5-d54a83ce8c65)

Name column doesn't seem to do anything, even if you successfully create a keybind the name value doesn't exist in any form in `input.conf`. It's being stripped down to `H           cycle fullscreen`

___
 

> I do my best to get great compatibility and mpv devs always help, but in some cases it's difficult.

As a end user i can only imagine, and simply thank you for all that time spent on development.

**Comment by stax76** [comment]
I'm working on it 3rd day now, it makes progress.

**Comment by stax76** [comment]
> In changelog it's mentioned that "Defining the context menu in input.conf is still supported, but discouraged and undocumented.", this created few issues/incompatibilities:

I wrote now to the manual that the old menu definition is fully supported.

> From what i understand, it's expected now to use Show input editor to define bindings or build context menu.

Editing input.conf manually is fully supported too.

> You can't use more than one modifier key when using Input editor, i.e. Ctrl+Alt+A is impossible to make.

Should be fixed now.

> Learn input popout only shows up when either command was already written, or you first activate name or command columns, and then jump back to it.

It wasn't designed to add new bindings, it existed because it was the default of the DataGrid control, it's now disabled.

> It would also be good if the popout had the typical "press any key" placeholder so it doesn't look like an empty box, but that's purely visual.

I made some changed in the learn window.

> When any new bind is added through Input editor it removes any commented-out and empty lines, so not only it deletes users formating, it also removes any "turned off" bindings. Basically deleting anything that starts with # without any notification to the user. This makes input.conf file mostly exclusive to mpv.net, and has potential config loss for the user.

I changed it to keep full line comments, and also empty lines.

> It even removes old separators in main context menu, but not submenus:

Should be fixed.

> also changes old #menu: syntax and replaces it with # menu: which potentailly adds up to another issue:

fixed

From the manual:

> Before version v7 all bindings and the context menu definition
> was contained in the input.conf file, which mpv.net created
> in case it didn't exist. This had the disadvantage that mpv.net
> lost control over all default bindings and the context menu
> defaults. This was unfortunate, v7 introduces a new design
> fixing it.
> 
> In v7 no input.conf file is created, the default bindings and
> context menu is defined internally. input.conf only contains
> what is different from the internally defined defaults,
> so it's the same how mpv is used.
> 
> For backward compatibility the old input.conf format with the
> menu definition using `#menu: ` is still supported. The new
> design also allows for a menu customization, in a sub section
> called `Custom`. In input.conf it can be defined like so:
> 
> `Ctrl+a  show-text Test  #custom-menu: Test > Test`

mpv.net modifies the input.conf content before it is passed to mpv in case of the new design being used. To make this transparent, there is a new command and menu item that shows what was passed to mpv:

View > Advanced > Show Bindings

script-message-to mpvnet show-bindings

I hope the new build is better, and I can react faster to helpful feedback.

There is some complexity, I hope it's not causing too many problems.

Before input.conf is written, a backup is copied to the system temp folder.

Thanks for the great bug report.

I changed the command_palette user script to strip `menu: ` when bindings are shown.

The new build:

https://github.com/mpvnet-player/mpv.net/actions/runs/6756760792

**Comment by stax76** [comment]
The next build can also read and write the short menu syntax with the exclamation mark, used by uosc.

**Comment by stax76** [comment]
Mention @Sneakpeakcss in case not subscribed.

**Comment by Sneakpeakcss** [comment]
Just checked it out, and it looks like context menus work without any issues, including the mentioned config/formating loss.

This is how the new default context menu looks like when old `#menu:` syntax isn't used in input.conf:


![mpvnet default menu](https://github.com/mpvnet-player/mpv.net/assets/77424331/c1b09513-f37f-4037-aa32-dbf5217d0bdc)

And i assume that the lack of separators in this case is by design, since this corresponds 1:1 to the config shown by `Show Bindings`
___

The only thing that's left seems to be this:

> - Uosc menu [syntax](https://github.com/tomasklaen/uosc#examples) is now broken for both uosc's compatibility `#menu:` and their native `#!` menu defining prefixes. Right now uosc doesn't even recognize it's own `#!` syntax, and outputs only it's own hardcoded default menu. This happens no matter if using old `input.conf` before `Input editor` goes through it removing stuff.

<sub>old mpv.net:</sub>

![old](https://github.com/mpvnet-player/mpv.net/assets/77424331/e98030da-0239-4906-8e18-3fe11340ffbe)

<sub>new mpv.net:</sub>

![new](https://github.com/mpvnet-player/mpv.net/assets/77424331/b0be548f-d395-4d12-a394-cc845786e9b7)

While `mpv.net` can now read `#!` syntax, uosc still doesn't see either of them. Other than that, everything works great, so thanks for the quick updates.

**Comment by stax76** [comment]
I noticed it too. Using the exact same settings (by using `--config-dir=.`) in mpv instead of mpv.net, it works. Correct input.conf content is passed to mpv as proven with the new `Show Bindings` feature. I hope I can find out what's wrong. Maybe uosc author @tomasklaen and @christoph-heinrich know what could be wrong.

**Comment by Sneakpeakcss** [comment]
From my limited understanding, in the newest mpv.net, `input-conf` returns(`print-text ${input-conf}`) the whole config file, in comparison to `nil` like it did before (and like mpv does), and [this](https://github.com/tomasklaen/uosc/blob/main/src/uosc/lib/menus.lua#L344 ) part of uosc doesn't like that, while the `input_conf_property` just pushes it forward to `-- File doesn't exist`. 

Forcing the path manually to `'~~/input.conf'` makes it work again in current `mpv.net`. So the question seems to be, which side is responsible to manage this scenario.

**Comment by stax76** [comment]
I think you found it. In mpv.net v7 input-conf is set from memory here:

https://github.com/mpvnet-player/mpv.net/blob/main/src/MpvNet/Player.cs#L105

It looks like something that can be fixed in uosc.

**Comment by christoph-heinrich** [comment]
If there is an is an easy way to check if it's running in mpv.net or not, then that should be a fairly easy fix, but why make it behave differently to how mpv behaves in the first place?

**Comment by christoph-heinrich** [comment]
I've whipped up a quick patch, but I'm not a windows user, so I can't test it.

```diff
diff --git a/src/uosc/lib/menus.lua b/src/uosc/lib/menus.lua
index 206fa72..3b59b50 100644
--- a/src/uosc/lib/menus.lua
+++ b/src/uosc/lib/menus.lua
@@ -341,20 +341,33 @@ do
 		if items then return items end
 
 		local input_conf_property = mp.get_property_native('input-conf')
-		local input_conf = input_conf_property == '' and '~~/input.conf' or input_conf_property
-		local input_conf_path = mp.command_native({'expand-path', input_conf})
-		local input_conf_meta, meta_error = utils.file_info(input_conf_path)
-
-		-- File doesn't exist
-		if not input_conf_meta or not input_conf_meta.is_file then
-			items = create_default_menu_items()
-			return items
+		local input_conf_iterator
+		if input_conf_property:sub(1, 9) == 'memory://' then
+			-- mpv.net v7
+			local input_conf_lines = split(input_conf_property:sub(10), '\n')
+			local i = 0
+			input_conf_iterator = function()
+				i = i + 1
+				return input_conf_lines[i]
+			end
+		else
+			local input_conf = input_conf_property == '' and '~~/input.conf' or input_conf_property
+			local input_conf_path = mp.command_native({'expand-path', input_conf})
+			local input_conf_meta, meta_error = utils.file_info(input_conf_path)
+
+			-- File doesn't exist
+			if not input_conf_meta or not input_conf_meta.is_file then
+				items = create_default_menu_items()
+				return items
+			end
+
+			input_conf_iterator = io.lines(input_conf_path)
 		end
 
 		local main_menu = {items = {}, items_by_command = {}}
 		local by_id = {}
 
-		for line in io.lines(input_conf_path) do
+		for line in input_conf_iterator do
 			local key, command, comment = string.match(line, '%s*([%S]+)%s+(.-)%s+#%s*(.-)%s*$')
 			local title = ''
 
```

**Comment by christoph-heinrich** [comment]
I just saw that v7 hasn't been released yet, so why not revert that change in behavior?

**Comment by stax76** [comment]
> It assumes that the string from mpv.net starts with memory://

Yes, it starts with `memory://`, I just checked.

> I just saw that v7 hasn't been released yet, so why not revert that change in behavior?

I release a beta version shortly, there are automated actions/workflow builds on every push (code contributed by dyphire). input-conf from memory is necessary for an important improvement, it's used to define binding defaults internally, the way it worked before was the biggest design flaw.

**Comment by stax76** [comment]
I tried the patch, it works now.
