### ISSUE TITLE
Support mpv title-bar option

### ISSUE THREAD

**Issue by candrapersada** [mpvnet-player/mpv.net#606]
is there support for [title-bar=no](https://github.com/tomasklaen/uosc/issues/811) in mpvnet?

**Comment by dyphire** [comment]
This function has not been implemented yet. refer      #574

**Comment by stax76** [comment]
The mpv code: https://github.com/mpv-player/mpv/pull/11469

**Comment by stax76** [comment]
I almost had it finished, there is just one issue I'm not able to fix.

**Comment by stax76** [comment]
There is hope.

**Comment by stax76** [comment]
It's done, after two days. But which OSC scripts support this well. Which OSC settings can I try?

**Comment by candrapersada** [comment]
how to use button without uosc
![image](https://github.com/mpvnet-player/mpv.net/assets/36833664/3872876a-75b8-4870-955f-4c0c5fa3d4e7)

**Comment by stax76** [comment]
There is a request for it here:

https://github.com/mpv-player/mpv/issues/13167
