### ISSUE TITLE
context menu mpvnet + context menu uosc

### ISSUE THREAD

**Issue by candrapersada** [mpvnet-player/mpv.net#607]
why [README.md](https://github.com/mpvnet-player/mpv.net/blob/main/README.md) or [manual.md](https://github.com/mpvnet-player/mpv.net/blob/main/docs/manual.md) no clear information on how to recreate it
```
mbtn_right           script-message-to mpvnet show-menu
_           ignore  #! Profile
_           script-message-to mpvnet show-conf-editor  #! Settings > Show Config Editor
_           script-message-to mpvnet show-input-editor  #! Settings > Show Input Editor
_           script-message-to mpvnet open-conf-folder  #! Settings > Open Config Folder

_           script-message-to mpvnet reg-file-assoc video  #! Settings > Setup > Register video file associations
_           script-message-to mpvnet reg-file-assoc audio  #! Settings > Setup > Register audio file associations
_           script-message-to mpvnet reg-file-assoc image  #! Settings > Setup > Register image file associations
_           script-message-to mpvnet reg-file-assoc unreg  #! Settings > Setup > Unregister file associations
```
if create input.conf new
mpv.net v7.0.0.1 Beta

**Comment by Sneakpeakcss** [comment]
[Not long ago](https://github.com/mpvnet-player/mpv.net/commit/9ec518a952434ad2f34c743cbba09860fe4b8587) support for `uosc` menu syntax was added to `mpv.net`, and since then i don't think there's an official way of separating them anymore. 
In case of `uosc` you could tinker with its [detection](https://github.com/tomasklaen/uosc/blob/b36cefed888c1cd2d4e0b667cc177d781c2af987/src/uosc/lib/menus.lua#L374) to remove mpv.net's menus, but that would still leave uosc's defined menus in mpv.net (unless you change every menu defining syntax, but that sounds like a unnecessary hassle). And if you're asking in general how to keep using both of them at once then i'm personally using [mpv-pointer-event](https://github.com/christoph-heinrich/mpv-pointer-event) with:

```
right_long=script-binding uosc/menu-blurred
right_single=script-message-to mpvnet show-menu
```
in its config.

**Comment by candrapersada** [comment]
`_           script-message-to mpvnet show-input-editor  #! Settings > Show Input Editor`
mpv.net v7.0.0.1 Beta
`_          script-message-to mpvnet show-input-editor    #menu: Settings > Show Input Editor`
mpv.net v6.0.4.0-stable

https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#input-and-context-menu
404 - page not found

**Comment by candrapersada** [comment]
![image](https://github.com/mpvnet-player/mpv.net/assets/36833664/3ce03d6d-f0d0-498e-a5b2-b976c6402430)
uosc
![image](https://github.com/mpvnet-player/mpv.net/assets/36833664/b0cbb9a6-b12b-40b0-9c9b-ff1d66e405d4)
mpvnet

**Comment by stax76** [comment]
> https://github.com/mpvnet-player/mpv.net/blob/main/src/Resources/input.conf.txt
> 404 - page not found

Where did you find this URL?

I added a `menu-syntax` option that allows you to define which syntax to use in mpv.net. I hope that solves your problem. A new build is online, find it here:

https://github.com/mpvnet-player/mpv.net/actions

**Comment by candrapersada** [comment]
> Where did you find this URL?

https://github.com/mpvnet-player/mpv.net/blob/308e3ed04470a5a7ff4e205a6910d37f1105a0b3/src/Resources/input.conf.txt
```
mbtn_right           script-message-to mpvnet show-menu
_           ignore  #! Profile
_           script-message-to mpvnet show-conf-editor  #! Settings > Show Config Editor
_           script-message-to mpvnet show-input-editor  #! Settings > Show Input Editor
_           script-message-to mpvnet open-conf-folder  #! Settings > Open Config Folder

_           script-message-to mpvnet reg-file-assoc video  #! Settings > Setup > Register video file associations
_           script-message-to mpvnet reg-file-assoc audio  #! Settings > Setup > Register audio file associations
_           script-message-to mpvnet reg-file-assoc image  #! Settings > Setup > Register image file associations
_           script-message-to mpvnet reg-file-assoc unreg  #! Settings > Setup > Unregister file associations
Ctrl+2      script-message-to mpvnet shell-execute https://github.com/mpvnet-player/mpv.net/blob/main/docs/manual.md  #! Help > Manual mpv.net
_           script-message-to mpvnet show-about  #! Help > About mpv.net
```

**Comment by stax76** [comment]
Is your problem with the menu with the last auto build solved?

**Comment by candrapersada** [comment]
`--menu-syntax=yes` context menu mpvnet and `--menu-syntax=no` context menu uosc not working

**Comment by stax76** [comment]
I've forgotten to add it to the conf editor, it's fixed in the last [auto build](https://github.com/mpvnet-player/mpv.net/actions).

**Comment by stax76** [comment]
It was a bug in the manual, it is:

--menu-syntax=\<value\>

Used menu syntax for defining the context menu in input.conf.\nmpv.net by default uses `#menu:`, uosc uses `#!` by default.

**Comment by Soromeister** [comment]
> ![image](https://private-user-images.githubusercontent.com/36833664/289704336-ba7bd737-9e12-4934-b9de-f3b5fa8ee707.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NDA5OTQsIm5iZiI6MTcwMjk0MDY5NCwicGF0aCI6Ii8zNjgzMzY2NC8yODk3MDQzMzYtYmE3YmQ3MzctOWUxMi00OTM0LWI5ZGUtZjNiNWZhOGVlNzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDIzMDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNjlhYThjODUyZjY1N2I0OGIzZjAzMGIwZmJjOGEyNmZmYmU5Y2UzOTZlM2M5NjY0MWU1YjBkMTMwZmYzNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AxfOfIMwmU76cAiEFPtLMNY1bGXYKdIAEqiUaF6dFY0) uosc

How do you get the `uosc` menu on the right click to show up instead of the `mpv.net` menu?
