### ISSUE TITLE
V7 bug: `save-position-on-quit` does not resume

### ISSUE THREAD

**Issue by TheBestPessimist** [mpvnet-player/mpv.net#608]
**Describe the bug**
After closing with `save-position-on-quit` and reopening the same file (double click in explorer), the last position is not restored, instead the video starts from 0.

**To Reproduce**
To reproduce, try the last beta version using the CLI option `--config=no`.

In case of an audio or video issue, try to reproduce the issue using mpv instead of mpv.net.
If it can be reproduced with mpv, use the [mpv issue tracker](https://github.com/mpv-player/mpv/issues).

1. use the mpv option `save-position-on-quit`
2. watch a video
3. quit video/mpv.net
4. restart the video

**Expected behavior**
Resuming from the same second as where i quit.

**Additional context**

Suggestion: please make a new menu under help named "Copy debug info" which takes all the information needed here. It should simply copy this to clipboard, so that i can paste it here.

1. mpv.net version
```
Copyright (C) 2000-2023 mpv.net/mpv/mplayer
mpv.net 7.0.0.1 (Monday, 11 December, 2023)
mpv v0.37.0-81-g443c2487 (Sunday, 10 December, 2023)
ffmpeg N-112937-gb9fd3e7a8
```
2. Windows version: Win 11 23H2
3. GPU name: intel

**Comment by TheBestPessimist** [comment]
Duplicate of: https://github.com/mpvnet-player/mpv.net/issues/565

**Comment by stax76** [comment]
I could reproduce it, then updated libmpv to zhongfly 2023-12-11 and with that it's fine. I had forgotten to update to a newer build.

**Comment by TheBestPessimist** [comment]
Hold on, isn't this a duplicate of #565  ?

**Comment by TheBestPessimist** [comment]
Duplicate of https://github.com/mpvnet-player/mpv.net/issues/565

**Comment by stax76** [comment]
It works here with `watch-later-options=start,pause,vid,aid,sid` and libmpv zhongfly from yesterday.

https://github.com/zhongfly/mpv-winbuild

**Comment by TheBestPessimist** [comment]
yes, that's true. but i had to manually add `watch-later-options=start` to my `mpv.conf`, whereas before i did not need that, even with the latest sourceforge mpv build. (hence the duplicate)

**Comment by stax76** [comment]
I now checked the mpv.net code and found there is `watch-later-options=mute`, so here is the problem. mpv.net sets this before the conf files are processed, so if you have better conf settings, you will be fine. I could have found this out earlier, sorry. 
I make a new beta release shortly, with a new libmpv build and using `watch-later-options=pause,start,vid,aid,sid`.

**Comment by TheBestPessimist** [comment]
As usual, don't need to apologise, it's a beta and there be dragons.
That's why we're here for anyway, to test it.
