### ISSUE TITLE
Issues with grouping multiple hotkeys for same command 

### ISSUE THREAD

**Issue by Sneakpeakcss** [mpvnet-player/mpv.net#610]
**Describe the bug**

In the newest beta the hotkeys for the same command are grouped together which creates rather amusing side effect when there's multiple:

![contextmenu1](https://github.com/mpvnet-player/mpv.net/assets/77424331/012f0b26-b1ad-48e0-a25b-c9644f9acaf2)

It's most certainly not preferable to have context menu scale its width like that, and maybe even not at all, since its not very good looking to have it so wide:

![image](https://github.com/mpvnet-player/mpv.net/assets/77424331/df51770e-1a88-4dcd-962c-8deb2dbfdee3)

 There also seems to be some parsing mistake where the last hotkey is added to the previous line as seen with `f` `F` and `Shift+Ctrl+Alt+Wheel_Down`.

Submenus seems to work slightly better by not grouping all of the hotkeys into a single line, but the mentioned parsing mistake still persists. And looks like they even cut the label name when there's not enough room for it in fullscreen:

![contextmenu2](https://github.com/mpvnet-player/mpv.net/assets/77424331/53ad426b-0315-4067-97a1-938defde8a83)

Add to input.conf:

```
F11         cycle fullscreen              #menu: Toggle Fullscreen1
f           cycle fullscreen		  #menu: Toggle Fullscreen2
g           cycle fullscreen
F           cycle fullscreen		  #menu: Toggle Fullscreen3
G           cycle fullscreen
F9           cycle fullscreen
Shift+Ctrl+Alt+Wheel_Down cycle fullscreen
Alt+MBTN_Forward cycle fullscreen
Alt+MBTN_Back cycle fullscreen
MBTN_Left_DBL  cycle fullscreen
KP_Enter    cycle fullscreen

Shift+Ctrl+Alt+Wheel_Down cycle fullscreen #menu: Navigate > this is kinda amusing
G           cycle fullscreen #menu: Navigate > this is kinda amusing
F9           cycle fullscreen #menu: Navigate > this is kinda amusing
Shift+Ctrl+Alt+Wheel_Down cycle fullscreen #menu: Navigate > this is kinda amusing
Alt+MBTN_Forward cycle fullscreen #menu: Navigate > this is kinda amusing
Alt+MBTN_Back cycle fullscreen #menu: Navigate > this is kinda amusing
MBTN_Left_DBL  cycle fullscreen #menu: Navigate > this is kinda amusing
KP_Enter    cycle fullscreen #menu: Navigate > this is kinda amusing
```

**Expected behavior**
I'm not exactly sure what would be the best behaviour for this. Allowing it to show multiple keys as long as there's room would be an option, but as seen on 2nd screenshot that still seems like a really weird formatting.

Maybe a dimmer color and lower font-size to better distinguish them from the label name, and a width limit based on the current "max context menu width" which seems to scale based on the longest label name, so the additional hotkeys (beside the 'main' first one) don't add up to the width.

1. mpv.net version: `v7.0.0.1-beta`
2. Windows version `Win10 22H2`

**Comment by stax76** [comment]
I made a commit fixing it, you can find a build here:

https://github.com/mpvnet-player/mpv.net/actions/runs/7185118320

**Comment by Sneakpeakcss** [comment]
Parsing mistake is fixed from what i can see, the rest is either expected or continuation of weird behaviour:

Any buttons that are associated with mouse buttons do not display at all (maybe intentionally filtered out because of their size ?):
```
Wheel_Down cycle fullscreen #menu: test
MBTN_Forward cycle fullscreen #menu: test2
MBTN_Back cycle fullscreen #menu: test
MBTN_Left_DBL  cycle fullscreen #menu: test
```

![image](https://github.com/mpvnet-player/mpv.net/assets/77424331/8ffd0540-b274-447f-838c-e505becf5644)

Similarly hotkeys with multiple modifiers:

```
Ctrl+Alt+b cycle fullscreen #menu: test
Ctrl+Alt+Shift+c  cycle fullscreen #menu: test2
```

![image](https://github.com/mpvnet-player/mpv.net/assets/77424331/a1e03087-ba21-40de-8e47-5b7368809430)

However adding a "visible" hotkey suddenly treats them as something requiring ellipsis:

```
Ctrl+Alt+b cycle fullscreen #menu: test
Ctrl+Alt+Shift+c  cycle fullscreen #menu: test2
d cycle fullscreen #menu: test
```

![image](https://github.com/mpvnet-player/mpv.net/assets/77424331/18d2b9a0-4a04-4a71-bb0e-4679098b3ecd)


And here's my default menu + the potentially amusing example again:
![image](https://github.com/mpvnet-player/mpv.net/assets/77424331/fd57fe79-5bd1-4ae3-98da-cb199a9a8104)

Personally i can't say that i'm a fan of this change in general, far too much clutter. Previous behaviour seem to be a better way of handling context menu where only the first defined hotkey was displayed, even more so when it's difficult to change the styling for hotkeys. 
If user defines multiple for the same command then it's on him to remember additional ones. This seems far more fitting for the previously removed mpv.net's integrated command menu, or a lua script, like your `command_palette` or `uosc` integrated menu:

![image](https://github.com/mpvnet-player/mpv.net/assets/77424331/c49cd47e-11fa-4bb0-94c0-36bfeddbd3e0)

**Comment by stax76** [comment]
> Any buttons that are associated with mouse buttons do not display at all (maybe intentionally filtered out because of their size ?):

> Similarly hotkeys with multiple modifiers:

This was because I excluded keys that are very long, not the best idea, I agree now.

New auto build is online, this time it works like this:

Ellipsis is no longer shown, there is one rule, that is the combined character length don't exceed 20 character.

Showing only one binding might not be liked by everybody, the reason why it shows more than one is it was requested by users.

I think it's at least okay now. I could add conf options, but this would be quite a bit of work.
