### ISSUE TITLE
Video positions not saving properly (quit-watch-later)

### ISSUE THREAD

**Issue by computator1200** [mpvnet-player/mpv.net#612]
**Describe the bug**
I have tried this with version 6.0.3.0 beta where it saves properly and that save can be loaded into both 6.0.3.0 and 6.0.4.0 but when trying to save 6.0.4.0 it seems to not do it properly and when that video is opened it plays from the start instead of the position it was saved on.

**To Reproduce**
To reproduce, try the last beta version using the CLI option `--config=no`.

1. Open a video and go somewhere in it
2. Exit watch later
3. Reopen that video
4. It will start from the beginning instead of where you stopped

**Expected behavior**
Should play the video from where it was stopped.

**Screenshots**

**Additional context**
1. mpv.net version 6.0.4.0
2. Windows 11 pro 22H2
3. RX 6700XT
4. Happening with all videos, tried mkv and mp4 formats

**Comment by stax76** [comment]
This happens because of a change in mpv that is not compatible with a poor default setting in mpv.net. You can probably work around it by putting the following configuration into your `mpv.conf`:

`watch-later-options = start,pause,vid,aid,sid`

Version v7.0.0.2 has it fixed.
