### ISSUE TITLE
add menu remove the Path environment variable.

### ISSUE THREAD

**Issue by candrapersada** [mpvnet-player/mpv.net#613]

**Comment by stax76** [comment]
You can remove it with the Windows UI.

In your Windows start menu, find it here:

`C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs`

Create a new shortcut:

**Name:** Environment Variables Editor

**Command line:** `rundll32.exe sysdm.cpl,EditEnvironmentVariables`

**Comment by stax76** [comment]
It will be available in the next beta release.
