### ISSUE TITLE
Can't get mpv.net to remember file position

### ISSUE THREAD

**Issue by WeekendWendy** [mpvnet-player/mpv.net#616]
This is all with a brand new v6.0.4.0-stable build and a clean AppData folder. I'm using Windows 10 Pro 21H2. I had this problem recently with mpv, also but it was related to file and folder permissions.

I can't get mpv.net to remember the file position. I know it's creating a file in AppData's watch_later with the current system time but has a file size of 0kb. It can remember volume though if set to yes.

I'm currently using ESC to quit with ESC quit-watch-later in input.conf. Also tried Capital Q and clicking X.

Thank you for any advice.

**Comment by stax76** [comment]
You can update to v7.0.0.3 beta or add a conf option:

`watch-later-options = start,pause,vid,aid,sid`

**Comment by WeekendWendy** [comment]
The option worked perfectly, thanks!
