### ISSUE TITLE
is there an option to choose to install mpv.net to the system or user?

### ISSUE THREAD

**Issue by candrapersada** [mpvnet-player/mpv.net#618]
system `C:\Program Files\mpv.net`
user `C:\Users\username\AppData\Local\mpv.net`

**Comment by stax76** [comment]
There is an installer which defaults to `C:\Program Files\mpv.net`, you did not find it?

**Comment by candrapersada** [comment]
what I mean is will there be an option to install mpv.net as a user?

**Comment by stax76** [comment]
I don't know how to do it with Inno Setup and don't plan to investigate it. Doesn't mean I don't listen if somebody knows Inno Setup well and makes a good suggestion.

**Comment by candrapersada** [comment]
![image](https://github.com/mpvnet-player/mpv.net/assets/36833664/33839390-5375-4c77-95b1-a298f8a89dd4)
https://itecnote.com/tecnote/installing-file-in-users-appdata-folder-using-inno-setup/

**Comment by soredake** [comment]
Better link https://stackoverflow.com/questions/15409739/installing-file-in-users-appdata-folder-using-inno-setup

**Comment by candrapersada** [comment]
are there any additional options if using the setup installer

1. Auto File Associations
2. Add mpv.net to Path environment variable system for mpv.net install in system. and Add mpv.net to Path environment variable user for mpv.net install in user or portable.

**Comment by stax76** [comment]
I think both links are insufficient. I believe it's supported by VapourSynth.

**Comment by soredake** [comment]
Example of the installer that supports both user and machine scope of installation https://github.com/marticliment/WingetUI/blob/main/WingetUI.iss

**Comment by stax76** [comment]
Thanks, supported in the next release.

**Comment by stax76** [comment]
> are there any additional options if using the setup installer or winget
> 
> 1. Auto File Associations if use setup installer or winget
> 2. Add mpv.net to Path environment variable system for mpv.net install in system. and Add mpv.net to Path environment variable user for mpv.net install in user or portable.

Both are difficult to do, especially when you don't understand Delphi, which most programmers don't.

https://stackoverflow.com/questions/3304463/how-do-i-modify-the-path-environment-variable-when-running-an-inno-setup-install

 I prefer doing it from within mpv.net because it's already done or easy to do.

In v7.0.0.3 there is:

- When mpv.net is started for the first time from a new startup location, it asks if mpv.net should be added to the Path environment variable.

I can do the same for file associations.

**Comment by candrapersada** [comment]
by default installing per user in non admin mode in winget.

**Comment by stax76** [comment]
> add by default installing per user in non admin mode in winget.

I don't know if it's possible and if so how it works.

There is a new beta version available with installer enhancement. Thanks for the feedback.

**Comment by soredake** [comment]
@stax76 https://jrsoftware.org/ishelp/index.php?topic=setupcmdline
This might work:
![image](https://github.com/mpvnet-player/mpv.net/assets/5204968/d88ce9a9-59a7-4eef-a43d-56724b8f022c)

**Comment by stax76** [comment]
The Inno Setup script is here:

https://github.com/mpvnet-player/mpv.net/blob/main/src/Setup/Inno/inno-setup.iss

winget has some relevant options:

`--silent --scope user`

I don't know if it's possible to apply these options by default by changing my winget manifest.

**Comment by soredake** [comment]
@stax76 i've done needed changes myself and submitted pr for 7.0.0.4 https://github.com/microsoft/winget-pkgs/pull/131151

**Comment by stax76** [comment]
Awesome, thanks. It took a couple of days until 7.0.0.3 got approved.

**Comment by stax76** [comment]
Thanks, @candrapersada and @soredake for the help.
