### ISSUE TITLE
Don't use reg keys with "first time startup from a new location questions" when using "portable_config" folder

### ISSUE THREAD

**Issue by BillyBob1354** [mpvnet-player/mpv.net#620]
**Is your feature request related to a problem? Please describe.**
The new "first time startup from a new location questions" feature uses a registry key even when using the "portable_config" folder.
If I move or rename the main mpv.net folder that's configured to be portable ("portable_config" folder) it asks the "first time startup questions" again.

**Describe the solution you'd like**
When using the "portable_config" folder don't ask the "first time startup questions" or add an configurable option to disable the "first time startup questions" thus no need to make the reg key.

**Describe alternatives you've considered**
When the "portable_config" folder is present save something to the "portable_config" folder instead of using the reg key.

**Comment by stax76** [comment]
I made two changes:

1. Use `settings.xml` in conf folder.
2. Use a list to prevent asking for the same folder more than once.

So it is very unintrusive now.

**Comment by stax76** [comment]
I removed the questions altogether.
