### ISSUE TITLE
Add Missing Strings to Multilingual File

### ISSUE THREAD

**Issue by nkh0472** [mpvnet-player/mpv.net#625]
**Describe the bug**
Certain strings are not present in the Transfix, resulting in an incomplete translation for the right-click menu.
(Also, all the strings in the config editor haven't been localization yet, but I guess that might need a lot of work...)

**To Reproduce**
1. Change the language to Chinese.
2. Right-click in the window to display the menu.
3. Alternatively, open the input editor.

**Expected behaviour**
All elements should be displayed in Chinese, but currently, some strings are in English. These strings are also absent from the Transfix file, making it impossible to translate them.

**Screenshots**
![image](https://github.com/mpvnet-player/mpv.net/assets/67589323/0456d15d-5174-44d3-800f-2cea1fc46002)
![image](https://github.com/mpvnet-player/mpv.net/assets/67589323/120a813b-4b88-4c64-b993-d1bbdf09ff86)
![image](https://github.com/mpvnet-player/mpv.net/assets/67589323/c6bdf7c5-d026-4c6c-a9e6-d736dd1231a9)

**Additional context**
1. mpv.net version: 7.0.0.4

**Comment by nkh0472** [comment]
By the way, now the language selection options are all shown in lowercase, which looks weird. Is it possible to capitalise the language list?

**Comment by stax76** [comment]
Transifex is now updated (13 new).

All options in the conf editor are lowercase, this is due to the command line nature of the options. Making changes or exceptions there would be very difficult because this code area is very complex.

**Comment by nkh0472** [comment]
> All options in the conf editor are lowercase, this is due to the command line nature of the options. Making changes or exceptions there would be very difficult because this code area is very complex.
Never mind, it's not a big problem:)

**Comment by stax76** [comment]
Thanks for the update, it'll be available in the next build.
