### ISSUE TITLE
Can it be used in Avalonia? Also, are there any recommended solutions for the Linux platform? We currently have a program developed based on the Avalonia framework, but we have not found a suitable RTSP player

### ISSUE THREAD

**Issue by Naylor55** [mpvnet-player/mpv.net#630]
Can it be used in Avalonia? Also, are there any recommended solutions for the Linux platform? We currently have a program developed based on the Avalonia framework, but we have not found a suitable RTSP player

**Comment by stax76** [comment]
You can find a list of cross-platform or Linux mpv frontends here:

https://github.com/stax76/awesome-mpv

The UI framework in use is listed too.
