### ISSUE TITLE
[Bugs] Hi! Friend! the colors are distorted and pixels are lost when playing the video in mpvnet.

### ISSUE THREAD

**Issue by zhouxinghong** [mpvnet-player/mpv.net#636]
Hi. - Hi! Friend! When will v7.0.0.7-beta be released please I want to try the new audio effects!😜

**Comment by stax76** [comment]
Hi! I don't know when I release it, so far it hasn't many improvements.

There are automatic builds, the last one is:

https://github.com/mpvnet-player/mpv.net/actions/runs/7404967162/artifacts/1146698793

You can find the builds on your own here:

https://github.com/mpvnet-player/mpv.net/actions

**Comment by zhouxinghong** [comment]
Also! Please upgrade the .net framework to .net 8.0 or we won't be able to run it!

**Comment by stax76** [comment]
I'm not 100% sure, but I think .NET 8 does not support Windows 7, some users are still using Windows 7.

**Comment by zhouxinghong** [comment]
Okay!
Found a problem, playing the video in mpvnet has completely different colors than playing the video in chrome, the colors are distorted and pixels are lost when playing the video in mpvnet.
Hope this issue can be solved effectively it!

**Comment by zhongfly** [comment]
more like an mpv config question

**Comment by zhouxinghong** [comment]
@zhongfly 
Hi! friend! Can you tell me what is the engine of mpvnet to play videos on Windows 10 system? Are you using the WebView2 engine provided by Microsoft? Or some other playback engine? So that I can determine the source of the problem. . .

**Comment by zhongfly** [comment]
> @zhongfly Hi! friend! Can you tell me what is the engine of mpvnet to play videos on Windows 10 system? Are you using the WebView2 engine provided by Microsoft? Or some other playback engine? So that I can determine the source of the problem. . .

read mpv manual, webview is not related to mpv.
https://mpv.io/manual/master/

**Comment by zhongfly** [comment]
> Okay! Found a problem, playing the video in mpvnet has completely different colors than playing the video in chrome, the colors are distorted and pixels are lost when playing the video in mpvnet. Hope this issue can be solved effectively it! Windows 10

please provide video sample, your mpv.conf and screenshot.
I think you can reproduce your problem with mpv too, and you can ask questions in mpv's issue

**Comment by zhouxinghong** [comment]
Example video:

https://github.com/mpvnet-player/mpv.net/assets/54253524/50fae3e6-90fc-441c-aebe-8323d46b5433

Re-step as follows:
1. Open the sample video provided above in mpvnet player;
2. Open the sample video provided above in the Chrome browser;
3. Observe the video color distortion in mpvnet player and Chrome browser respectively.

Windows 10 19044

**Comment by zhouxinghong** [comment]
![image](https://github.com/mpvnet-player/mpv.net/assets/54253524/261385f7-d851-4e73-b6d5-f2a1c08725a4)

**Comment by Sneakpeakcss** [comment]
`chrome`
![chrome](https://github.com/mpvnet-player/mpv.net/assets/77424331/6f9b0cf3-e538-404c-98e2-7ce2f6211a39)

`mpv.net --no-config`
![mpvnet](https://github.com/mpvnet-player/mpv.net/assets/77424331/866ae52b-4e19-42b8-be8f-d5de8fc2c2c3)

`firefox`
![firefox](https://github.com/mpvnet-player/mpv.net/assets/77424331/524e9fa9-9b66-4eef-b306-44c3298c7809)

Color differences between browsers is [expected](https://help.vimeo.com/hc/en-us/articles/12425821202961-Troubleshoot-color-variation) and anyone who did any video editing knows the pain surrounding it. 

The difference in color between `chrome` and default `mpv.net` are barely noticeable on my end, and `mpv.net` is without any difference to default `mpv`, so its unlikely that this is mpv.net's fault.

Other video players also have color discrepancy, where `mpc-hc` is closer to `chrome` and `vlc` is closer to `mpv`.
Simply using [--icc-profile-auto](https://mpv.io/manual/master/#options-icc-profile-auto) we again get something even different:

`mpv.net --no-config --icc-profile-auto`
![mpvnet-iccprofileauto](https://github.com/mpvnet-player/mpv.net/assets/77424331/39c62dda-c083-4245-a2b6-f05e284d4311)

In `mpv.net` settings, there are few options that might have any influence on this, like chosen profile preset or [vo-gpu-next](https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU), and those options are most likely not exhaustive, it's just some of them exposed in a menu for user convenience. 

Currently, you should get an mpv [build](https://github.com/zhongfly/mpv-winbuild/releases) and see if it behaves the same as `mpv.net`. If so, then it's either a question/bug report for [mpv repo](https://github.com/mpv-player/mpv).

Though, if your nickname serves as a hint, then you might have easier time with pre-configured projects like those made by [hooke007](https://github.com/hooke007/MPV_lazy) or [dyphire](https://github.com/dyphire/mpv-config), especially dyphires reference links: [参考](https://github.com/dyphire/mpv-config#%E5%8F%82%E8%80%83)

**Comment by zhouxinghong** [comment]
1. As I mentioned last time, I suspect that this problem is caused by the video rendering engine.
2. Also, how to use the `--icc-profile-auto` and `vo-gpu-next` parameters in mpvnet? Can you give an example? Thank you very much!
