### ISSUE TITLE
Unexpected FPS drop and frame delay when opening console in mpvnet

### ISSUE THREAD

**Issue by averagePedestrian** [mpvnet-player/mpv.net#637]
I’m currently using the latest version of mpvnet on Windows 10 22H2. My laptop is equipped with a Nvidia GTX 1660ti, running driver version 537.58. Regardless of the GPU API I use, I notice a drop in estimated FPS and an increase in mistimed and delayed frames whenever I open the built-in console. Is this expected behavior? If not, what could be the potential cause of this issue?

![Default behaviour](https://github.com/mpvnet-player/mpv.net/assets/24970562/b52b7ffa-4096-45e0-9c9c-12c3a040217c)
![with console](https://github.com/mpvnet-player/mpv.net/assets/24970562/9b5a5fa6-1d98-460f-9360-f47d3472c31b)

**Comment by Sneakpeakcss** [comment]
I really doubt that this is an `mpv.net` issue. Try using [mpv](https://github.com/zhongfly/mpv-winbuild/releases) and check if it still persists. 

As a sidenote, you can clear the console by pressing `Ctrl+l`
