### ISSUE TITLE
Is there an option to turn off `Hidden Features` ?

### ISSUE THREAD

**Issue by Sneakpeakcss** [mpvnet-player/mpv.net#638]
Well, i just now discovered that `mpv.net` has a [feature](https://github.com/mpvnet-player/mpv.net/blob/main/docs/manual.md#hidden-features) where it closes the player when top-right corner is pressed in both `fullscreen` and `border=off`, and was wondering if there's an option to turn this off ? 

It _kind of_ gets in the way of using scripts that rely on user input to get positioning, like `crop.lua` and maybe even scripts that create their own 'control menu' in that corner. 

I think [this](https://github.com/mpvnet-player/mpv.net/blob/304fe58f278e172c6195f11c3e240628b9e35ac8/src/MpvNet.Windows/WinForms/MainForm.cs#L1403-L1412) is the relevant code, but i didn't manage to find anything configurable.

**Comment by stax76** [comment]
It cannot be turned off. It's probably okay to simply remove the feature.

**Comment by Sneakpeakcss** [comment]
Yea, if there's no option to turn that off then that's probably the best action, especially when it's quite obscure to the point of being literally called hidden. Not a good function to discover randomly like i did.

**Comment by stax76** [comment]
Ok, it's gone with the next commit.
