### ISSUE TITLE
Context menu no longer opens in certain `settings.xml` conditions.

### ISSUE THREAD

**Issue by Sneakpeakcss** [mpvnet-player/mpv.net#639]
**Describe the bug**

Since changes in https://github.com/mpvnet-player/mpv.net/commit/edcd8be6624a37573db4b0c59dd7557f8b7c9dfb, the context menu no longer opens when a `-` path is added to `<RecentFiles>`. This kind of path is added when opening livestreams through [streamlink](https://github.com/streamlink/streamlink).

**To Reproduce**

```xml
<?xml version="1.0" encoding="utf-8"?>
<AppSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <InputDefaultBindingsFixApplied>true</InputDefaultBindingsFixApplied>
    <ShowMenuFixApplied>true</ShowMenuFixApplied>
    <MenuUpdateVersion>1</MenuUpdateVersion>
    <Volume>70</Volume>
    <RecentFiles>
        <string>-</string>
    </RecentFiles>
    <WindowLocation>
        <X>0</X>
        <Y>0</Y>
    </WindowLocation>
    <WindowPosition>
        <X>0</X>
        <Y>0</Y>
    </WindowPosition>
    <WindowSize>
        <Width>0</Width>
        <Height>0</Height>
    </WindowSize>
    <AudioDevice />
    <ConfigEditorSearch>Video:</ConfigEditorSearch>
    <Mute>no</Mute>
    <StartupFolder />
</AppSettings>
```

1. Add the above to `settings.xml`

**Expected behavior**

Well… Context menu should open lol.

**Additional context**

This technically happens even before the write to `settings.xml` (at least for that single instance of `mpv.net`), at the point when a 'video' with this path is loaded.

 

1. **mpv.net version:** every build since https://github.com/mpvnet-player/mpv.net/commit/edcd8be6624a37573db4b0c59dd7557f8b7c9dfb
2. **Windows version:** `WIN10 22H2`

**Comment by stax76** [comment]
Good it was found before the release.
