### ISSUE TITLE
A Problem in Japanese Translation

### ISSUE THREAD

**Issue by tsubasanouta** [mpvnet-player/mpv.net#644]
I would you to separate "up/down" strings in volume menu and "up/down" strings in move menu  in Transifex.
These strings are different expressions in Japanese.

**Comment by stax76** [comment]
I researched how to add context and found out how it works and pushed changes to transifex.

**Comment by tsubasanouta** [comment]
Thank you so much for updating some strings.
Would you please update Japanese translation when you have time?

**Comment by stax76** [comment]
Thanks for completing the Japanese translation. I've pulled it from transifex and created the mo file, so it will be available in the next release.
