### ISSUE TITLE
Question: How do I make the title gray in a regular mpv?

### ISSUE THREAD

**Issue by AdventurerRussia** [mpvnet-player/mpv.net#647]
I can't find how to change the color, I really like the gray color as you came out.
![image](https://github.com/mpvnet-player/mpv.net/assets/14019010/0cea3f7a-097a-4bd6-8bbf-75a803f344db)

**Comment by stax76** [comment]
You mean, how to do this with code? This is a feature that should already be supported by mpv and also by mpv.net.

```C#
    void UpdateDarkMode()
    {
        if (Environment.OSVersion.Version >= new Version(10, 0, 18985))
            DwmSetWindowAttribute(Handle, 20, new[] { Theme.DarkMode ? 1 : 0 }, 4);  // DWMWA_USE_IMMERSIVE_DARK_MODE = 20
    }
```

**Comment by AdventurerRussia** [comment]
yes, it works when you turn on the dark theme throughout the system, but it works for you when it is light for applications. So I'm asking how you can always turn on the dark one, is there any way?

**Comment by stax76** [comment]
mpv.net has an option for this:

dark-mode <always|system|never>

I searched the mpv manual for 'dark' and couldn't find an option. You can make a feature request.
