### ISSUE TITLE
Rotating video with hwdec enabled breaks colors v7.1.0.0 

### ISSUE THREAD

**Issue by ll811** [mpvnet-player/mpv.net#652]
**Describe the bug**
video either loses all color when rotated or it just breaks them in one way or another.  Does not occur with hwdec disabled. 

**To Reproduce**
Play any video with hwdec enabled and rotate the video 90 degrees 

1. Enable hwdec
2. Start video
3. Rotate video 
3. See error

**Expected behavior**
For the video to rotate without breaking colors.

**Additional context**
1. mpv.net v7.1.0.0 
2. Windows 10 OS build 19045.3930 
3. RTX 3070 with 551.23 driver

**Comment by Sneakpeakcss** [comment]
Sounds more like a `mpv` issue https://github.com/mpv-player/mpv/issues/8223 

There's few workarounds for this scattered around, but no real fix from what i know. You can try try either using `--cscale=bilinear` or [this](https://github.com/hooke007/MPV_lazy/blob/5ee1250106e29adc900d8f01099962824849e7e1/portable_config/profiles.conf#L169-L175) conditional profile from `MPV_lazy`
