### ISSUE TITLE
Bug: MPV starts remaining time from zero in mid of video

### ISSUE THREAD

**Issue by pstein** [mpvnet-player/mpv.net#659]
Have a look at the attached MP4 file

I put it into *.zip archive to be sure that the file server does not change anything.
This (extracted) video should have a total length of ~56 seconds.

When I start playing it with MPV.net v7.1.1.0 on Windows 10 then MPV.net shows at first a remaining time of only 30 seconds.
After these 30 seconds MOV.net resets the remaining time to 26 seconds and starts from 0.
Why does MPV.net not start with a remaining time of all together 56 seconds?

This is a bug.

**Comment by pstein** [comment]
[Output.zip](https://github.com/mpvnet-player/mpv.net/files/14236313/Output.zip)

**Comment by Sneakpeakcss** [comment]
Same thing happens in `mpv` player, so this is not really a `mpv.net` issue. And from the look of it, the video is broken. Both `ffprobe` and `mediainfo` display errors, and the file also doesn't seem to have keyframes after 30s mark:
```
0.000000,I,
10.000000,I
17.080000,I
27.080000,I
29.520000,I
30.000000,I
```

So this is a matter of botched video download.
