### ISSUE TITLE
How do I make the screenshot with subtitles look like the way I see it on my screen?

### ISSUE THREAD

**Issue by tarantinosaur** [mpvnet-player/mpv.net#660]
Sorry for not using the template. 

This has been a thing I've noticed since version 5. Is there a way to make the screenshot look like how I see it on my screen?

This is what I see:
![screen screenshot](https://github.com/mpvnet-player/mpv.net/assets/36843667/a54bd491-4546-47c7-a29f-19bb5a7f8ec7)

This is what mpv captures:
![mpv screenshot](https://github.com/mpvnet-player/mpv.net/assets/36843667/3f66b9eb-c24e-4795-9769-8cacd4d03221)

**Comment by Sneakpeakcss** [comment]
Check `mpv` [documentation](https://mpv.io/manual/master/#command-interface-screenshot-%3Cflags%3E). 

You most likely want `screenshot window` which will take a screenshot of the whole window as is. 

Bear in mind that this will take a screenshot with everything that is currently displayed on the screen, so if you want them to be clean then you have to create a keybind for it in `input.conf`, and also dimensions are based on window state, so windowed/fullscreen will have different dimensions and not correspond to video resolution.
