### ISSUE TITLE
Add support for "input-media-keys" option

### ISSUE THREAD

**Issue by seagull** [mpvnet-player/mpv.net#662]
**Is your feature request related to a problem? Please describe.**
MPV supports a feature in the mpv.conf file called "input-media-keys" that can be set to NO to stop MPV from stealing media key input. I would like MPV.net to also support this feature so I can use my media keys to control my music without affecting a video playing in the foreground. Currently the setting does nothing in 7.1.1.0.

**Comment by Dregu** [comment]
I second this. I only want to use media keys to control spotify, but having mpv.net open in the background, without any media key bindings and `input-media-keys=no` in the config still just disables all my media keys globally.

Ideally this wouldn't be behind a catch-all yes/no option either, but specific media keys should be possible to capture globally when specified in the config, while others do nothing and still work in other programs.

**Comment by stax76** [comment]
Here using mpv or mpv.net, it doesn't matter if `input-media-keys=yes` or `input-media-keys=no` is set or if mpv or mpv.net is focused or not, when I change the volume with the media keys, always the system volume changes and not the mpv or mpv.net volume. I'm using Windows 11. The mpv manual states 'Whether media keys work when the mpv window is focused is implementation-defined.', it's possibly OS or hardware/driver specific, without being able to reproduce it, it's difficult to fix. I made a change you can try here:

https://github.com/mpvnet-player/mpv.net/actions/runs/10728525105/artifacts/1898560486

**Comment by seagull** [comment]
Hi @stax76 ,
For what it's worth, your volume keys won't be any use. The key to try is `PLAY/PAUSE`. If your keyboard doesn't have such a key, you can test using the KeyTweak program to re-map a button you don't normally use to serve that purpose (maps are reversible but each change requires a reboot).

More importantly, your new version works! With `input-media-keys = no` in `mpv.conf`, pausing media makes my music stop/start as desired.  
Thank you!

**Comment by stax76** [comment]
OK, thanks for testing.
