### ISSUE TITLE
Whats the difference between MPV and mpv.net player? Is it a fork?

### ISSUE THREAD

**Issue by pstein** [mpvnet-player/mpv.net#664]
When investigation MPV player I f found two similar video players:

MPV  (from https://mpv.io/installation/)
and 
mpv.net

What are the differences?
Is one a fork of the other?

**Comment by succumbs** [comment]
i don't mean to come off as rude at all, but this is quite a dumb thing to make an issue over. did you even try to read the readme? it answers all your questions.
