### ISSUE TITLE
The very basic necessity of showing your "Playlists" feature are missing?!

### ISSUE THREAD

**Issue by TheSeriousYoungBoy** [mpvnet-player/mpv.net#670]
**Is your feature request related to a problem? Please describe.**
Showing the playlist is one of the most basic necessities of a media player, I can't believe one would remove such a very useful tool to watch your own media files. Even VLC has it as a free-open-source project.

**Describe the solution you'd like**
Please bring back or create a simple "Show Playlist/F8" specifically for MPV.NET, it just doesn't sit right with me that there's no such basic functionality in the media player.

**Describe alternatives you've considered**
Even a simple playlist window is good enough like VLC's or if that's not simplier enough, adding a functionality where your playlists could pop-out as texts on the current video playing, and there, you can actually use your arrow keys to toggle which video you would like to play/modify/delete is simply enough...

**Additional context**
You already gave it as one of the four available options to choose from, it's better if we can simply manually enable it in the app.
(https://github.com/jonniek/mpv-playlistmanager) for a much more vibrant experience. Thanks.

**Comment by stax76** [comment]
This will be addressed in the next release.

> Full support for select.lua which is a new simple command palette script embedded into mpv/libmpv. In the context menu select.lua features can be found under 'View > On Screen Menu'. https://github.com/mpv-player/mpv/blob/master/player/lua/select.lua

```
F8          script-binding select/select-playlist  #menu: View > On Screen Menu > Playlist
F1          script-binding select/select-binding  #menu: View > On Screen Menu > Bindings
F3          script-binding select/show-properties  #menu: View > On Screen Menu > Properties
Alt+c       script-binding select/select-chapter  #menu: View > On Screen Menu > Chapters
Alt+t       script-binding select/select-track  #menu: View > On Screen Menu > Tracks
_           script-binding select/select-aid  #menu: View > On Screen Menu > Audio Tracks
_           script-binding select/select-sid  #menu: View > On Screen Menu > Subtitle Tracks
Alt+F2      script-binding select/select-secondary-sid  #menu: View > On Screen Menu > Secondary Subtitle
Alt+v       script-binding select/select-vid  #menu: View > On Screen Menu > Video Tracks
Alt+l       script-binding select/select-subtitle-line  #menu: View > On Screen Menu > Subtitle Lines
Alt+d       script-binding select/select-audio-device  #menu: View > On Screen Menu > Audio Devices
```
