### ISSUE TITLE
Request to Add a New Language

### ISSUE THREAD

**Issue by Jambickz** [mpvnet-player/mpv.net#673]
I would like to propose adding a new language to mpv.net - Russian. The translation process was facilitated with the integration of ChatGPT's AI assistance, ensuring accuracy and coherence throughout the translation.

**Translation File:**
[ru.txt](https://github.com/mpvnet-player/mpv.net/files/14749877/ru.txt)

**Proposal:**
Adding the Russian language will significantly expand the user base and make mpv.net more accessible to Russian-speaking audiences. The translation, aided by ChatGPT's AI, has been done attentively and with high quality, considering the context of usage and localization standards.

_Additional Information:_
If necessary, I am willing to make adjustments to the translation to ensure its accuracy and compliance with the program's standards.

**Thank you for considering this request.**

**Comment by PystoyPlayer** [comment]
Что ж, я разобрался, как это можно сделать вручную. Пути до папок видимо захардкодены, но можно заменить немецкий перевод на русский, например. Особо не запаривался, поэтому прогнал через Гугл ну и чуть откровенный бред поправил. Взял TXT чела сверху, сразу конвертировать в POT не смог, но [localazy](https://localazy.com/p/123-2010) распознала английскую локализацию, её я там сам перевёл и экспортировал в POT. А [POT уже перевёл в MO](https://po2mo.net). В менюшке кстати не перевелась кнопка video, но лень чинить, да и есть ли смысл, кому надо, хорошо бы нормально перевод допилить, все инструкции я вам предоставил.
[ru.mo.zip](https://github.com/mpvnet-player/mpv.net/files/15002355/ru.mo.zip)
![IMAGE 2024-04-17 12:06:03 AM](https://github.com/mpvnet-player/mpv.net/assets/88878911/8ec817a4-0f23-4a2d-9707-3f94304126bb)
https://github.com/mpvnet-player/mpv.net/assets/88878911/37134e7d-eabf-466d-8f27-0680ca8a868f

**Comment by mvv82** [comment]
https://forum.ru-board.com/topic.cgi?forum=5&topic=8528&start=1560#8

**Comment by Jambickz** [comment]
Есть форум где люди активно обсуждают данную программу, кастомизируют по своему. Я думаю там можно много полезного зайти.
Вот - [https://forum.ru-board.com/topic.cgi?forum=5&topic=8528](Link)

**Comment by stax76** [comment]
Thanks for the contribution, Jambickz! I updated the mpv files locally and also transifex with your translation.

If you are interested, you can register an account at transifex, I can add you then to the mpv.net translation team on transifex.

https://app.transifex.com/stax76/teams/
