### ISSUE TITLE
Controls stop working after switching vo via settings

### ISSUE THREAD

**Issue by CatKasha** [mpvnet-player/mpv.net#677]
**Describe the bug**
Controls stop working after switching vo via settings

**To Reproduce**
1. Launch mpv.net
2. Open settings
3. Change vo option to something else instead currently used
4. Exit settings window
5. Keyboard and mouse (osc and right click menu) сontrols stop working

**Expected behavior**
vo changes should not break controls

**Additional context**
1. mpv.net 7.1.1.0 (03.02.2024)
2. Windows 10 21H2 / 10.0.19044
3. AMD Radeon RX 6600

**Comment by BlackPowerade** [comment]
This also occurs if you change the VO via changing the active profile.

Also I don't know if this is related, but it looks like windows doesn't properly show mpv.net's icon anymore. instead it shows the vanilla mpv icon

**Comment by stax76** [comment]
It's an upstream mpv problem.
