### ISSUE TITLE
Video stutters when on fullscreen on one screen and other maximized window on second screen

### ISSUE THREAD

**Issue by karnasw** [mpvnet-player/mpv.net#679]
**Describe the bug**
When I play fullscreen video on one screen and browsing internet on second screen with maximized browser than video stutters. Issue not exist when video isn't fullscreen or browser (example) isn't maximized or mpv.net windows is active.

**To Reproduce**
Play video fullscreen with mpv.net on first screen and maximize browser or other windows on second screen, keep second screen window active.

**Expected behavior**
No stuttering.

**Additional context**
1. mpv.net 7.1.1.0
2. Windows version
3. NVidia GTX 1070
4. Media info: HEVC, 3840x2160, 128Mb/s, 59.94FPS

**Comment by karnasw** [comment]
I think it's mpv bug. Tried [mpv-x86_64-v3-20240421-git-b364e4a.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20240421-git-b364e4a.7z/download) and same happens.

**Comment by Sneakpeakcss** [comment]
I have similar issue, but surprisingly the other way around. Keeping `mpv` in fullscreen on secondary monitor lags every windows animation (most noticeable with opening folders), but the moment there's any window maximized on primary then everything works fine, but like you noticed this is a `mpv` thing, so you'll have more luck reporting it there.

**Comment by karnasw** [comment]
Reported on mpv github: https://github.com/mpv-player/mpv/issues/13966
