### ISSUE TITLE
Stay on top button in internal title bar

### ISSUE THREAD

**Issue by regs01** [mpvnet-player/mpv.net#681]
It would be really very useful to have ability to quickly switch stay on top with mouse only.
<img width="419" alt="mpvnet_2024-04-28_15-15-38" src="https://github.com/mpvnet-player/mpv.net/assets/10468217/2235ea31-c504-4de9-b03f-f9ccb1a6eb12">

**Comment by regs01** [comment]
> ctlr+t to toggle stay on top

Yes, that requires keyboard

**Comment by CatKasha** [comment]
mpv itself is not convenient to use without keyboard

**Comment by b-cpu** [comment]
> Yes, that requires keyboard, but it's not convinient.

here i am always thinking applications these days aren't convenient to use when they force me to use the mouse lol
such a weird statement to me

**Comment by stax76** [comment]
This title bar is implemented in a built-in script called osc.lua which is part of mpv and not mpv.net.
