### ISSUE TITLE
regarding net compatibility (mouse handling with script extension)

### ISSUE THREAD

**Issue by wooshaq** [mpvnet-player/mpv.net#684]
Hello, how much compatible net is vs vanilla? I'm running into some problems with this script that sadly works partially since double clicking is only registered when mouse is moving, when cursor is still I need to click 3 times and super fast for it to register. On regular mpv it works properly, is this salvageable?

https://github.com/natural-harmonia-gropius/input-event

**Comment by stax76** [comment]
There are mouse compatibility limitations that are too difficult to fix.
