### ISSUE TITLE
How to add menu items at the top of the menu

### ISSUE THREAD

**Issue by chwt163** [mpvnet-player/mpv.net#690]
I wanted to put 'open files' on top alone, but I didn't want to use the old version of 'input.conf', In 'input editor', delete 'File >' does not make it possible to put 'open files' at the top.
Is it possible to provide a new version of the full 'input.conf' to make this change?

Like this:

![捕获](https://github.com/mpvnet-player/mpv.net/assets/70951194/f27bb2dc-c10f-4bd6-a648-c76e4e323693)

**Comment by stax76** [comment]
There is a legacy/compatibility mode:

> Before version v7 all bindings and the context menu definition were defined in the input.conf file, which mpv.net created in case it didn't exist. This had the disadvantage that mpv.net lost control over all default bindings and context menu defaults. This was unfortunate, v7 introduces a new bindings and context menu design fixing it.
> 
> In v7 no input.conf file is created, the default bindings and context menu is defined internally. input.conf only contains what is different from the internally defined defaults, so it works the same as it works in mpv.
> 
> For backward compatibility the old input.conf context menu format with the menu definition using #menu:  is still supported. The new design also allows for a menu customization, in a sub section called Custom. In input.conf it can be defined like so:

I don't recommend using the legacy mode, in the context menu, try `View > More > Show Bindings`.

**Comment by chwt163** [comment]
I see, thanks!
