### ISSUE TITLE
Remember the last screen player was on

### ISSUE THREAD

**Issue by himankpathak** [mpvnet-player/mpv.net#693]
**Is your feature request related to a problem? Please describe.**
I have a multi-monitor setup when launching the app from Explorer, the player launches on the screen where the Explorer window is. I have to either leave the player open on the screen so new files launch on the same screen or else I have to manually move the player again and again to the correct screen.

**Describe the solution you'd like**
The solution should be a setting similar to the `start-size` setting which remembers the previous screen size, we can have a setting `start-screen` which allows the user to set a mode that launches the player in the same previous screen it was open.

**Describe alternatives you've considered**
I am aware of the `screen` variable in config, which lets you set a default screen and always forces the mpv player to open on that monitor. That is what I am currently using but it is restrictive not exactly the behavior I want from the app.

**Comment by Sneakpeakcss** [comment]
Isn't [remember-window-position=yes](https://github.com/mpvnet-player/mpv.net/blob/ae9c69e469160d28626a3e24aa915f219a1020c9/docs/manual.md#--remember-window-positionyesno) exactly what you describe?

**Comment by himankpathak** [comment]
Thanks @Sneakpeakcss !
I completely missed this setting. This is exactly what I needed.
