### ISSUE TITLE
"Settings > Edit [mpv,input].conf" silently fails if the file does not exist

### ISSUE THREAD

**Issue by Mattwmaster58** [mpvnet-player/mpv.net#696]
**Describe the bug**
If `mpv.conf` or `input.conf` do not exist, the context menu -> settings -> Edit [mpv,input].conf options will silently fail

**To Reproduce**
 - Ensure mpv or input.conf do not exist at the expected path
 - attempt to use menu option to edit them

**Expected behavior**
At minimum, I believe an error should be shown, or ideally IMHO the file created if it does not exist.

**Screenshots**
N/A

**Additional context**
1. mpv.net version: `mpv.net 7.1.1.0 (2024-02-03)`

**Comment by stax76** [comment]
The next build will ask if the file should be created.
