### ISSUE TITLE
Would it be possible to add "cursor-autohide"?

### ISSUE THREAD

**Issue by StefenStefan** [mpvnet-player/mpv.net#702]
**Is your feature request related to a problem? Please describe.**
No, it would just be nice if the cursor could be hidden faster.

**Describe the solution you'd like**
/

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by stax76** [comment]
The next mpv.net release will support `cursor-autohide`.

> Tired of the cursor randomly no auto hiding.

There is a limitation documented here:

https://github.com/mpvnet-player/mpv.net/blob/main/docs/manual.md#window-limitations

**Comment by StefenStefan** [comment]
Thank you so much, appreciate it!

**Comment by stax76** [comment]
You're welcome. I've released a new beta version today.
