### ISSUE TITLE
Why is the new MPV.Net creating a cache folder?

### ISSUE THREAD

**Issue by Digita1Menace** [mpvnet-player/mpv.net#706]
In my portable config. and it keeps growing. and I'm simply playing movies from my pc. no streams. How do I disable. I dont like folders that grow and grow and I got to remember to delete them.

**Comment by stax76** [comment]
It's probably from a mpv script, thumbfast maybe.

**Comment by Digita1Menace** [comment]
> It's probably from a mpv script, [thumbfast](https://github.com/po5/thumbfast) maybe.

I dont see how. 1st I'm not using thumbfast [right now] I switch from 6.0.3.0-beta (portable) to mpv.net-v7.1.1.0-portable and simply copied over my scripts.
scripts I use are:
audio-osc.lua
autoload.lua
bookmarker-menu.lua
chapter_frame_only.lua
chapter_make_read.lua
Ignore-file-types.lua
pause-replay.lua
webm.lua

**Comment by Digita1Menace** [comment]
Ill just removed the scripts and script-ops folders, opened a video and it created the cache folder again.
Not a script doing it.

**Comment by Digita1Menace** [comment]
I just took one of the cache files [they have no extensions) added .txt to the end, opened it in notepad++ and this is what it reads, it's shaders:
![image](https://github.com/user-attachments/assets/62d28420-b23a-41e0-a28e-3eb3747edcb3)

**Comment by stax76** [comment]
I googled it and found:

https://github.com/mpv-player/mpv/issues/11898

**Comment by stax76** [comment]
I'm closing it because it is an upstream issue.

**Comment by Digita1Menace** [comment]
> I googled it and found:
> 
> [mpv-player/mpv#11898](https://github.com/mpv-player/mpv/issues/11898)

No, it's a stupid file build-up issue. I disabled it with that link earlier today, but thanks.
