### ISSUE TITLE
When playing videos, can the choice between calling d3d11 or Vulkan be made based on the video encoding? 

### ISSUE THREAD

**Issue by dunkeng** [mpvnet-player/mpv.net#708]
On my computer, the performance of Vulkan is excellent, but it does not support some older video formats, and I have to switch to D3D11 to decode the videos properly. Is there a way to determine the video encoding format to choose between Vulkan or d3d11?

**Comment by stax76** [comment]
I'm not experienced in this topic, but found some info here:

https://mpv.io/manual/master/#options-hwdec

If that don't help, you have a better chance to get help here:

https://www.reddit.com/r/mpv

**Comment by dunkeng** [comment]
Thank you for your reply.
I have tried some methods and was unable to achieve what I needed. 
Since the mainstream video files are still H.264/H.265, I decided to install VLC as an alternative player to switch to VLC for playback when Vulkan is not supported. 
This is a simpler solution that I can implement.
