### ISSUE TITLE
v7.1.1.2-beta broke Bookmarker Menu v1.3.1 for mpv 

### ISSUE THREAD

**Issue by Digita1Menace** [mpvnet-player/mpv.net#711]
it works for the stable release, but I grabbed the Beta for the mouse pointer bux fix, which so far works.
I go to load a bookmark, it says success but it will not load the movie now.
It WILL load the current movie you are watching if you make a bookmark, but once you close MPV.Net and reopen, that bookmark will not load. only works on a current playing movie. Weird..
https://github.com/NurioHin/mpv-bookmarker

**Comment by stax76** [comment]
Maybe mpv had a breaking change, are there error messages printed on the terminal?

**Comment by Digita1Menace** [comment]
> Maybe mpv had a breaking change, are there error messages printed on the terminal?

Terminal? you mean on screen. it just shows the normal:
![mpvnet_Tegnit4A7Q](https://github.com/user-attachments/assets/6e3cbf7d-e034-4f5f-b8ff-b85d3f2430b5)

**Comment by stax76** [comment]
In case of errors, mpv and mpv scripts print errors to the terminal. If you want to see errors, start mpv.net from a powershell terminal.

1. In the mpv.net context menu: Settings > Setup > Add mpv.net to Path...
2. Start a new PowerShell terminal session.
3. Enter `mpvnet` and press enter.

See if it prints any error messages.

**Comment by Digita1Menace** [comment]
> In case of errors, mpv and mpv scripts print errors to the terminal. If you want to see errors, start mpv.net from a powershell terminal:
> 
>     1. In the mpv.net context menu: Settings > Setup > Add mpv.net to Path...
> 
>     2. Start a new PowerShell terminal session.
> 
>     3. Enter `mpvnet` and press enter.
> 
> 
> See if it prints any error messages.
I dont have that option
![image](https://github.com/user-attachments/assets/bb133435-bb54-4b1f-a922-db4134f1b0cc)

**Comment by stax76** [comment]
In the on-screen console, you can get it with:

`script-message-to mpvnet add-to-path`

**Comment by stax76** [comment]
You can open input.conf and see if it contains 'console'.

**Comment by Digita1Menace** [comment]
> You can open input.conf and see if it contains 'console'.

It's under view> advanced>show console. here are the two errors on the bottom:
![image](https://github.com/user-attachments/assets/9b02b436-f4c0-4b2f-9aa8-ce1b77ccc171)

**Comment by stax76** [comment]
There is also something wrong with input bindings, I quit for today, see you tomorrow.

**Comment by stax76** [comment]
I can take a look in your input.conf if you post the content here or at pastebin.com.

**Comment by Digita1Menace** [comment]
> I can take a look in your input.conf if you post the content here or at pastebin.com.

it's messy. should I be quoting you for you to get an email? 
anyway:
https://pastebin.com/wqPfydPv

**Comment by Digita1Menace** [comment]
I can upload my whole portable MPV if you need it to sort this out. besides this small issue, there is only one more thing preventing the player from being perfect. It creeps up the screen after constantly loading more files. I think I made an issue ticket but I may have only asked on reddit..

**Comment by stax76** [comment]
I needed some time to figure it out, even though the issue is obvious.
In the terminal, the error message says:

Unknown key 'script-message-to'

So I checked all lines in your input.conf that contain `script-message-to`

Problem is in line 64:

```
MBTN_Left_DBL cycle fullscreen
          script-message-to mpvnet show-playlist #menu: View > Show Playlist
h          script-message-to mpvnet show-history #menu: Tools > Show History
```

If you don't want to assign a key, you can use and underscore:

`_          script-message-to mpvnet show-playlist #menu: View > Show Playlist`

mpv even gives the line number where the issue is, at the end of the error message.

`[input] _          script-message pause-replay:64`

**Comment by Digita1Menace** [comment]
That did not fix it. new:
![image](https://github.com/user-attachments/assets/56b844ca-4c50-4aae-b90f-6832ddd08a9a)

**Comment by Digita1Menace** [comment]
OK so I removed every script and script-op except bookmaker. still broke, however I just realized that that is not the original script. someone modified it on Reddit for me o I could have the bookmarker.json is my portable folder in stead of app data crap.

So maybe something he did is interfering with you cursor fix.

**Comment by Digita1Menace** [comment]
this is the issue, whatever it means..
![image](https://github.com/user-attachments/assets/3a31ba2e-678d-414f-af5e-5301f038ef04)

**Comment by Digita1Menace** [comment]
Is this why?
https://github.com/NurioHin/mpv-bookmarker/issues/20

**Comment by stax76** [comment]
@NurioHin

Many scripts allow paths being customizable.

Sample code:
