### ISSUE TITLE
How to hide the Mpv or Mpv.net Logo at start up?

### ISSUE THREAD

**Issue by YingDoge** [mpvnet-player/mpv.net#712]
Are there anyway that you could do that? 
it icon the line below it is very annoying?

Thanks

**Comment by YingDoge** [comment]
![image](https://github.com/user-attachments/assets/3a03f992-bcb2-42a4-8d21-134d508a5667)
From here i tried

osc-hidelogo = no

that did not work somehow.

**Comment by YingDoge** [comment]
![image](https://github.com/user-attachments/assets/cd5db521-14d5-46b1-a994-ef8313e4d87b)

Tried both 

idlescreen = false

idlescreen = no

in the osc.conf

that did not work too

**Comment by YingDoge** [comment]
osc-idlescreen = no

![image](https://github.com/user-attachments/assets/b409e4af-36ae-45ca-a825-9a0f9d786d6b)

this does not work too.

**Comment by HornyPrivateGamer** [comment]
At start up, hmmmmm so far there is no solution on the internet right now. 
you might need @stax76, he is master at this.

**Comment by stax76** [comment]
This command line works:

`mpv --script-opts=osc-idlescreen=no`

In the conf files, be sure there is no space character before and after the equal character. This works only in mpv.conf and not for other conf files.

**Comment by YingDoge** [comment]
> This command line works:
> 
> `mpv --script-opts=osc-idlescreen=no`
> 
> In the conf files, be sure there is no space character before and after the equal character. This works only in mpv.conf and not for other conf files.

i tired it right now. It does work 
![image](https://github.com/user-attachments/assets/09e1c46b-d95d-476a-924a-535f4f0a858c)

**Comment by YingDoge** [comment]
> This command line works:
> 
> `mpv --script-opts=osc-idlescreen=no`
> 
> In the conf files, be sure there is no space character before and after the equal character. This works only in mpv.conf and not for other conf files.

That i am not using the newest version of MPV.net just saying could that be a reason that it is not working ?

**Comment by YingDoge** [comment]
> This command line works:
> 
> `mpv --script-opts=osc-idlescreen=no`
> 
> In the conf files, be sure there is no space character before and after the equal character. This works only in mpv.conf and not for other conf files.


# Editor
vo = gpu
gpu-context = d3d11
hwdec = nvdec-copy
ao = wasapi
volume = 100
osc = no
hr-seek-framedrop = no
sub-auto = fuzzy
audio-file-auto = fuzzy
idle = no
autofit = 80
autofit-smaller = 80
autofit-larger = 80
osd-font-size = 35
osd-level = 


tscale = oversample
dscale = ewa_lanczossharp
hdr-compute-peak = no
allow-delayed-peak-detect = no
cscale = ewa_lanczossharp
dither-depth = 12
dither = error-diffusion
osd-on-seek = no
screenshot-format = png
screenshot-png-compression = 5
screenshot-jpeg-quality = 100
screenshot-png-filter = 5
screenshot-template = '~~MPV Screen Shots/MPV-%P-N%n'
sigmoid-upscaling = yes
linear-downscaling = yes
correct-downscaling = yes
video-output-levels = full
fullscreen = no
blend-subtitles = yes
sub-font-size = 55
sub-ass-vsfilter-color-compat = full
audio-spdif = ac3,eac3,dts-hd,truehd


vf = 'format:dolbyvision=yes'
vd-lavc-dr = yes
hwdec-codecs = 'all'
slang = 'zh,chi,chs,sc,zho,en,eng'
alang = jpn,Japanese,en,eng, zh,chi,chs,sc,zho,


hls-bitrate = max
snap-window = yes
osd-scale-by-window = yes
keep-open = yes
fbo-format = rgba16hf
#if strong enough pc use rgba32f
loop-file = no
icc-cache-dir = '~~/icc_cache'
gpu-shader-cache-dir = '~~/shaders_cache'
priority = high
hidpi-window-scale = yes



deinterlace = no
sub-ass-vsfilter-aspect-compat = no
image-subs-video-resolution = yes
image-lut-type = native
lut-type = native
save-position-on-quit = yes
cursor-autohide = always
osd-bar = no


#cache-on-disk =
tone-mapping-mode = rgb

video-aspect-override = -1

audio-pitch-correctio = yes
interpolation = yes
tone-mapping = hable
gamut-mapping-mode = clip

scale = ewa_lanczossharp


osd-font-size = 35


audio-channels=auto-safe
icc-profile-auto = yes

script-opts-append=keep_session-auto_load=yes

mpv --script-opts=osc-idlescreen=no

**Comment by stax76** [comment]
You need this file:

`script-opts/osc.conf`

With this content:

`idlescreen=no`

**Comment by YingDoge** [comment]
> You can configure the osc with this file:
> 
> `script-opts/osc.conf`
> 
> This config should work:
> 
> `idlescreen=no`

![image](https://github.com/user-attachments/assets/49d253de-9193-4435-a132-2599c50a6911)
![image](https://github.com/user-attachments/assets/4edcbdea-c9d3-435e-a259-57df9159cd32)

I am sorry, that i is still not working
i am created the file osc.conf in script-opts and stilll nothign changed.

I apoliges for taking so much of your time collaborator

**Comment by stax76** [comment]
You can run mpv in a terminal and see error messages in the terminal.

**Comment by HornyPrivateGamer** [comment]
> You can run mpv in a terminal and see error messages in the terminal.

what code should i used to show the error sorry sir.

**Comment by YingDoge** [comment]
> You can run mpv in a terminal and see error messages in the terminal.

what code should i run to seee the erros sir. Sorry a bit of noob here

**Comment by stax76** [comment]
You can add mpv.net to the Path environment variable from the mpv.net menu:

`Settings > Setup > Add mpv.net to the Path environment variable`

Then in the terminal to can run mpv.net by typing `mpvnet` followed with Enter key.

After that, you might see error messages.

https://www.google.com/search?q=path+environment+variable+windows

**Comment by HornyPrivateGamer** [comment]
![image](https://github.com/user-attachments/assets/34cd766d-bda4-4d2d-9278-cf29c4635a6b)


> You can add mpv.net to the Path environment variable from the mpv.net menu:
> 
> `Settings > Setup > Add mpv.net to the Path environment variable`
> 
> Then in the terminal to can run mpv.net by typing `mpvnet` followed with Enter key.
> 
> After that, you might see error messages.
> 
> https://www.google.com/search?q=path+environment+variable+windows

The terminal said this error for teh code you give me

**Comment by HornyPrivateGamer** [comment]
> You can add mpv.net to the Path environment variable from the mpv.net menu:
> 
> `Settings > Setup > Add mpv.net to the Path environment variable`
> 
> Then in the terminal to can run mpv.net by typing `mpvnet` followed with Enter key.
> 
> After that, you might see error messages.
> 
> https://www.google.com/search?q=path+environment+variable+windows

![Screenshot 2024-10-23 194208](https://github.com/user-attachments/assets/fc88325c-f93b-4de8-9271-d28ac54dfb5d)

Settings > Setup > Add mpv.net to the Path environment variable

which of those options,  dont know why this is in chinese but this is the newest version i dolwoaded from MPV.net

**Comment by YingDoge** [comment]
> ettings > Setup > Add mpv.net to the Path environment variable

https://www.youtube.com/watch?v=6YSYAo4UXow 
i am following this video to do the path environment, is this video correct?

**Comment by YingDoge** [comment]
@stax76 I found the reaosn why 
![image](https://github.com/user-attachments/assets/3f594e30-998b-4a17-9d58-e34b64ef0ca7)
That in Modern X 
https://github.com/zydezu/ModernX
Thre is a option "Welcome Screen' that over ride the setting in MPV.net 
how to disabel it to
1. go to you folder and open the ModernX Script 
2. than find the welcomescreen , than change it to: False

this like 
welcomescreen = false,           -- show the mpv 'play files' screen upon open
