### ISSUE TITLE
Cooked x_x

### ISSUE THREAD

**Issue by JIGASHI** [mpvnet-player/mpv.net#716]
What the happened to this project. 3 years ago or so, no problems, now it does not even have history function and I read and tried the guides on getting that to work.

It should have a setup where you on first launch configure everything with live previews. and check-boxes, you click a checkbox some looped video next to it shows the change you made as described next to the check-box.

Prioritize users time, it's like Linux, a black hole of autism. VLC is too much in the other direction, why can't they look at what MPV did right and implement it. Fucking hell.

This many years in and the popularity, one would presume it would have been done years ago.

**Comment by notjiatan** [comment]
> Prioritize users time, it's like Linux, a black hole of autism
😭
